/*
 * Copyright 2025 Alex Soloviov (aka Theko)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.theko.sound;

import static org.theko.sound.properties.AudioSystemProperties.AUTOMATIONS_UPDATE_TIME;

import java.util.List;

import org.theko.sound.control.AudioControl;
import org.theko.sound.control.AudioControlGroup;
import org.theko.sound.control.Controllable;
import org.theko.sound.control.EnumControl;
import org.theko.sound.control.FloatControl;

/**
 * Low Frequency Oscillator (LFO) for modulating audio parameters over time.
 * <p>
 * An LFO generates periodic waveforms that can be applied to any {@link AudioControl} 
 * or group of controls in an audio system. This allows dynamic modulation of parameters 
 * such as volume, filter cutoff, pitch, or any custom effect parameter.
 * </p>
 * <p>
 * Features:
 * <ul>
 *   <li>Supports configurable waveform type via {@link WaveformType}.</li>
 *   <li>Controls include <b>amount</b>, <b>phase</b>, <b>speed</b>, <b>attack</b>, and <b>base</b>.</li>
 *   <li>Runs in a background thread and continuously updates associated controls.</li>
 *   <li>Supports dynamic addition and removal of controls at runtime.</li>
 * </ul>
 * </p>
 * 
 * <p><b>Example usage:</b></p>
 * <pre>{@code
 * // Create an LFO that modulates a specific control
 * FloatControl cutoff = new FloatControl("Filter Cutoff", 20f, 20000f, 1000f);
 * LFO lfo = new LFO(List.of(cutoff));
 * 
 * // Configure parameters
 * lfo.getSpeed().setValue(0.5f);
 * lfo.getAmount().setValue(0.8f);
 * lfo.getWaveformType().setEnumValue(WaveformType.SINE);
 * 
 * // Start the LFO
 * lfo.start();
 * }</pre>
 * 
 * @since 2.3.2
 * @author Theko
 */
public class LFO implements Controllable {

    protected final FloatControl amount = new FloatControl("Amount", 0.0f, 1.0f, 0.5f);
    protected final FloatControl phase = new FloatControl("Phase", 0.0f, 1.0f, 0.0f);
    protected final FloatControl speed = new FloatControl("Speed", 0.001f, 100.0f, 0.5f);
    protected final FloatControl attack = new FloatControl("Attack", 0.0f, 10.0f, 1.0f);
    protected final FloatControl base = new FloatControl("Base", -100.0f, 100.0f, 0.5f);

    /** Type of waveform generated by this LFO. */
    protected final EnumControl waveformType = new EnumControl("Waveform", WaveformType.SINE);

    /** Update interval in milliseconds for applying LFO values. */
    protected final int updateTime;
    protected static final int DEFAULT_UPDATE_TIME = AUTOMATIONS_UPDATE_TIME;

    /** List of LFO's internal controls for easy access. */
    protected final List<AudioControl> lfoControls = List.of(amount, phase, speed, attack, base, waveformType);

    /** Flag indicating whether the LFO is currently running. */
    protected volatile boolean isPlaying;

    /** Group of controls managed by this LFO. */
    protected final AudioControlGroup controlGroup;

    /**
     * Creates a new LFO with the specified controls and update interval.
     * 
     * @param controls the list of {@link AudioControl} objects this LFO will modulate
     * @param updateTime the update interval in milliseconds
     */
    public LFO(List<AudioControl> controls, int updateTime) {
        controlGroup = new AudioControlGroup(controls);
        this.updateTime = updateTime;
    }

    /**
     * Creates a new LFO with the specified controls and the default update interval.
     * 
     * @param controls the list of {@link AudioControl} objects this LFO will modulate
     */
    public LFO(List<AudioControl> controls) {
        this(controls, DEFAULT_UPDATE_TIME);
    }

    /** Adds a control to be modulated by this LFO. */
    public void addControl(AudioControl control) {
        controlGroup.addControl(control);
    }

    /** Removes a control from modulation by this LFO. */
    public void removeControl(AudioControl control) {
        controlGroup.removeControl(control);
    }

    /** @return the amount control. */
    public FloatControl getAmount() {
        return amount;
    }

    /** @return the phase control. */
    public FloatControl getPhase() {
        return phase;
    }

    /** @return the speed control. */
    public FloatControl getSpeed() {
        return speed;
    }

    /** @return the attack control. */
    public FloatControl getAttack() {
        return attack;
    }

    /** @return the base control. */
    public FloatControl getBase() {
        return base;
    }

    /** @return the waveform type control. */
    public EnumControl getWaveformType() {
        return waveformType;
    }

    /** Starts the LFO if it is not already running. */
    public void start() {
        if (!isPlaying) {
            isPlaying = true;
            AutomationsThreadPool.submit(this::process);
        }
    }

    /** Stops the LFO if it is currently running. */
    public void stop() {
        isPlaying = false;
    }

    /**
     * Background process that continuously updates control values.
     * <p>
     * Should only be called internally by the automation system.
     * </p>
     */
    protected void process() {
        long startTime = System.nanoTime();
        while (!Thread.currentThread().isInterrupted()) {
            long currentTime = System.nanoTime();
            float timeDelta = (currentTime - startTime) / 1_000_000_000.0f;
            float value = getValue(timeDelta);
            controlGroup.apply(value);
            try {
                Thread.sleep(updateTime);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                break;
            }
        }
    }

    /**
     * Calculates the LFO output value at a given time.
     * 
     * @param time time in seconds since the LFO started
     * @return the computed LFO value
     */
    public float getValue(float time) {
        float phaseValue = (speed.getValue() * time + phase.getValue()) % 1f;
        float waveformValue = WaveformGenerator.generate((WaveformType) waveformType.getEnumValue(), phaseValue);
        float envelope = attack.getValue() > 0f ? Math.min(time / attack.getValue(), 1f) : 1f;
        return base.getValue() + amount.getValue() * waveformValue * envelope;
    }

    /** @return the {@link AudioControlGroup} managed by this LFO. */
    public AudioControlGroup getControls() {
        return controlGroup;
    }

    @Override
    public List<AudioControl> getAllControls() {
        return lfoControls;
    }
}
