/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.backends.wasapi.WASAPISharedBackend'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/backends/wasapi/WASAPISharedBackend
class Java_org_theko_sound_backends_wasapi_WASAPISharedBackend {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized
        jclass clazz;
        jfieldID fld__logger; // private static final org.slf4j.Logger org.theko.sound.backends.wasapi.WASAPISharedBackend.logger
        jfieldID fld__lib32; // private static final java.io.File org.theko.sound.backends.wasapi.WASAPISharedBackend.lib32
        jfieldID fld__lib64; // private static final java.io.File org.theko.sound.backends.wasapi.WASAPISharedBackend.lib64
        jfieldID fld__backendContextPtr; // private long org.theko.sound.backends.wasapi.WASAPISharedBackend.backendContextPtr
        jfieldID fld__isInitialized; // private boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isInitialized
        jfieldID fld__isSupported; // private static final boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isSupported
        jmethodID ctor__; // public org.theko.sound.backends.wasapi.WASAPISharedBackend()
        jmethodID mtd__shutdown; // public void org.theko.sound.backends.wasapi.WASAPISharedBackend.shutdown() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__initialize; // public void org.theko.sound.backends.wasapi.WASAPISharedBackend.initialize() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat; // public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getPort(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getDefaultPort_org_theko_sound_AudioFlow; // public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getDefaultPort(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isInitialized; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isInitialized()
        jmethodID mtd__getInputBackend; // public org.theko.sound.backends.AudioInputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getInputBackend()
        jmethodID mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat,java.util.concurrent.atomic.AtomicReference) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat; // public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getAvailablePorts_org_theko_sound_AudioFlow; // public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getAllPorts; // public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAllPorts() throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isAudioPortSupported_org_theko_sound_AudioPort; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAudioPortSupported(org.theko.sound.AudioPort)
        jmethodID mtd__getOutputBackend; // public org.theko.sound.backends.AudioOutputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getOutputBackend()
        jmethodID mtd__isAvailableOnThisPlatform; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAvailableOnThisPlatform()
        jmethodID mtd__equals_java_lang_Object; // public boolean java.lang.Object.equals(java.lang.Object)

        Java_org_theko_sound_backends_wasapi_WASAPISharedBackend(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/backends/wasapi/WASAPISharedBackend");
            if (!clazz_local) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to find class 'org.theko.sound.backends.wasapi.WASAPISharedBackend'");
                return;
            }

            // Constructors
            ctor__ = env->GetMethodID(clazz_local, "<init>", "()V");
            if (!ctor__) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.backends.wasapi.WASAPISharedBackend()'");
                return;
            }

            // Fields
            fld__logger = env->GetStaticFieldID(clazz_local, "logger", "Lorg/slf4j/Logger;");
            if (!fld__logger) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'logger'");
                return;
            }
            fld__lib32 = env->GetStaticFieldID(clazz_local, "lib32", "Ljava/io/File;");
            if (!fld__lib32) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'lib32'");
                return;
            }
            fld__lib64 = env->GetStaticFieldID(clazz_local, "lib64", "Ljava/io/File;");
            if (!fld__lib64) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'lib64'");
                return;
            }
            fld__backendContextPtr = env->GetFieldID(clazz_local, "backendContextPtr", "J");
            if (!fld__backendContextPtr) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'backendContextPtr'");
                return;
            }
            fld__isInitialized = env->GetFieldID(clazz_local, "isInitialized", "Z");
            if (!fld__isInitialized) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'isInitialized'");
                return;
            }
            fld__isSupported = env->GetStaticFieldID(clazz_local, "isSupported", "Z");
            if (!fld__isSupported) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'isSupported'");
                return;
            }

            // Methods
            mtd__shutdown = env->GetMethodID(clazz_local, "shutdown", "()V");
            if (!mtd__shutdown) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'shutdown'");
                return;
            }
            mtd__initialize = env->GetMethodID(clazz_local, "initialize", "()V");
            if (!mtd__initialize) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'initialize'");
                return;
            }
            mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "getPort", "(Lorg/theko/sound/AudioFlow;Lorg/theko/sound/AudioFormat;)Ljava/util/Optional;");
            if (!mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getPort'");
                return;
            }
            mtd__getDefaultPort_org_theko_sound_AudioFlow = env->GetMethodID(clazz_local, "getDefaultPort", "(Lorg/theko/sound/AudioFlow;)Ljava/util/Optional;");
            if (!mtd__getDefaultPort_org_theko_sound_AudioFlow) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getDefaultPort'");
                return;
            }
            mtd__isInitialized = env->GetMethodID(clazz_local, "isInitialized", "()Z");
            if (!mtd__isInitialized) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isInitialized'");
                return;
            }
            mtd__getInputBackend = env->GetMethodID(clazz_local, "getInputBackend", "()Lorg/theko/sound/backends/AudioInputBackend;");
            if (!mtd__getInputBackend) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getInputBackend'");
                return;
            }
            mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference = env->GetMethodID(clazz_local, "isFormatSupported", "(Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;Ljava/util/concurrent/atomic/AtomicReference;)Z");
            if (!mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isFormatSupported'");
                return;
            }
            mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "isFormatSupported", "(Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;)Z");
            if (!mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isFormatSupported'");
                return;
            }
            mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "getAvailablePorts", "(Lorg/theko/sound/AudioFlow;Lorg/theko/sound/AudioFormat;)Ljava/util/Collection;");
            if (!mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getAvailablePorts'");
                return;
            }
            mtd__getAvailablePorts_org_theko_sound_AudioFlow = env->GetMethodID(clazz_local, "getAvailablePorts", "(Lorg/theko/sound/AudioFlow;)Ljava/util/Collection;");
            if (!mtd__getAvailablePorts_org_theko_sound_AudioFlow) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getAvailablePorts'");
                return;
            }
            mtd__getAllPorts = env->GetMethodID(clazz_local, "getAllPorts", "()Ljava/util/Collection;");
            if (!mtd__getAllPorts) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getAllPorts'");
                return;
            }
            mtd__isAudioPortSupported_org_theko_sound_AudioPort = env->GetMethodID(clazz_local, "isAudioPortSupported", "(Lorg/theko/sound/AudioPort;)Z");
            if (!mtd__isAudioPortSupported_org_theko_sound_AudioPort) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isAudioPortSupported'");
                return;
            }
            mtd__getOutputBackend = env->GetMethodID(clazz_local, "getOutputBackend", "()Lorg/theko/sound/backends/AudioOutputBackend;");
            if (!mtd__getOutputBackend) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getOutputBackend'");
                return;
            }
            mtd__isAvailableOnThisPlatform = env->GetMethodID(clazz_local, "isAvailableOnThisPlatform", "()Z");
            if (!mtd__isAvailableOnThisPlatform) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isAvailableOnThisPlatform'");
                return;
            }
            mtd__equals_java_lang_Object = env->GetMethodID(clazz_local, "equals", "(Ljava/lang/Object;)Z");
            if (!mtd__equals_java_lang_Object) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'equals'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            
            initialized = true;
        }

    public:
        ~Java_org_theko_sound_backends_wasapi_WASAPISharedBackend() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* get(JNIEnv* env) {
            if (!env) return nullptr;
            if (!Java_org_theko_sound_backends_wasapi_WASAPISharedBackend::jvm) {
                env->GetJavaVM(&Java_org_theko_sound_backends_wasapi_WASAPISharedBackend::jvm);
            }
            static std::mutex mtx;
            static std::unique_ptr<Java_org_theko_sound_backends_wasapi_WASAPISharedBackend> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!instance || !instance->isValid()) {
                instance.reset(new Java_org_theko_sound_backends_wasapi_WASAPISharedBackend(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Field getters
        inline static jfieldID getfld__logger(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__logger;
        }
        inline static jfieldID getfld__lib32(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__lib32;
        }
        inline static jfieldID getfld__lib64(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__lib64;
        }
        inline static jfieldID getfld__backendContextPtr(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__backendContextPtr;
        }
        inline static jfieldID getfld__isInitialized(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__isInitialized;
        }
        inline static jfieldID getfld__isSupported(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__isSupported;
        }

        // Constructor getters
        inline static jmethodID getctor__(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__;
        }

        // Method getters
        inline static jmethodID getmtd__shutdown(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__shutdown;
        }
        inline static jmethodID getmtd__initialize(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__initialize;
        }
        inline static jmethodID getmtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__getDefaultPort_org_theko_sound_AudioFlow(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getDefaultPort_org_theko_sound_AudioFlow;
        }
        inline static jmethodID getmtd__isInitialized(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isInitialized;
        }
        inline static jmethodID getmtd__getInputBackend(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getInputBackend;
        }
        inline static jmethodID getmtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference;
        }
        inline static jmethodID getmtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__getAvailablePorts_org_theko_sound_AudioFlow(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getAvailablePorts_org_theko_sound_AudioFlow;
        }
        inline static jmethodID getmtd__getAllPorts(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getAllPorts;
        }
        inline static jmethodID getmtd__isAudioPortSupported_org_theko_sound_AudioPort(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isAudioPortSupported_org_theko_sound_AudioPort;
        }
        inline static jmethodID getmtd__getOutputBackend(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getOutputBackend;
        }
        inline static jmethodID getmtd__isAvailableOnThisPlatform(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isAvailableOnThisPlatform;
        }
        inline static jmethodID getmtd__equals_java_lang_Object(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__equals_java_lang_Object;
        }

        // Fabric methods for constructors
        // Instance creation method for public org.theko.sound.backends.wasapi.WASAPISharedBackend()
        inline static jobject createInstance(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor);
        }

        // Method wrappers
        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedBackend.shutdown() throws org.theko.sound.backends.AudioBackendException
        inline static void shutdown(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__shutdown;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedBackend.initialize() throws org.theko.sound.backends.AudioBackendException
        inline static void initialize(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__initialize;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getPort(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getPort(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getDefaultPort(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getDefaultPort(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getDefaultPort_org_theko_sound_AudioFlow;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isInitialized()
        inline static jboolean isInitialized(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isInitialized;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd);
        }

        // Fabric method for public org.theko.sound.backends.AudioInputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getInputBackend()
        inline static jobject getInputBackend(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getInputBackend;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat,java.util.concurrent.atomic.AtomicReference) throws org.theko.sound.backends.BackendNotOpenException
        inline static jboolean isFormatSupported__org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference(JNIEnv* env, jobject obj, jobject v0, jobject v1, jobject v2) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0, v1, v2);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        inline static jboolean isFormatSupported__org_theko_sound_AudioPort__org_theko_sound_AudioFormat(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getAvailablePorts__org_theko_sound_AudioFlow__org_theko_sound_AudioFormat(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getAvailablePorts__org_theko_sound_AudioFlow(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getAvailablePorts_org_theko_sound_AudioFlow;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0);
        }

        // Fabric method for public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAllPorts() throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getAllPorts(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getAllPorts;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAudioPortSupported(org.theko.sound.AudioPort)
        inline static jboolean isAudioPortSupported(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isAudioPortSupported_org_theko_sound_AudioPort;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0);
        }

        // Fabric method for public org.theko.sound.backends.AudioOutputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getOutputBackend()
        inline static jobject getOutputBackend(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getOutputBackend;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAvailableOnThisPlatform()
        inline static jboolean isAvailableOnThisPlatform(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isAvailableOnThisPlatform;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd);
        }

        // Fabric method for public boolean java.lang.Object.equals(java.lang.Object)
        inline static jboolean equals(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedBackend* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__equals_java_lang_Object;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0);
        }

    // End of class declaration
};
