/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.backends.wasapi.WASAPISharedOutput'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/backends/wasapi/WASAPISharedOutput
class Java_org_theko_sound_backends_wasapi_WASAPISharedOutput {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized
        jclass clazz;
        jfieldID fld__logger; // private static final org.slf4j.Logger org.theko.sound.backends.wasapi.WASAPISharedOutput.logger
        jfieldID fld__outputContextPtr; // private long org.theko.sound.backends.wasapi.WASAPISharedOutput.outputContextPtr
        jfieldID fld__isOpen; // private boolean org.theko.sound.backends.wasapi.WASAPISharedOutput.isOpen
        jfieldID fld__isStarted; // private boolean org.theko.sound.backends.wasapi.WASAPISharedOutput.isStarted
        jfieldID fld__bufferSize; // private int org.theko.sound.backends.wasapi.WASAPISharedOutput.bufferSize
        jfieldID fld__audioFormat; // private org.theko.sound.AudioFormat org.theko.sound.backends.wasapi.WASAPISharedOutput.audioFormat
        jfieldID fld__port; // private org.theko.sound.AudioPort org.theko.sound.backends.wasapi.WASAPISharedOutput.port
        jmethodID ctor__; // public org.theko.sound.backends.wasapi.WASAPISharedOutput()
        jmethodID mtd__flush; // public void org.theko.sound.backends.wasapi.WASAPISharedOutput.flush() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isOpen; // public boolean org.theko.sound.backends.wasapi.WASAPISharedOutput.isOpen() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__start; // public void org.theko.sound.backends.wasapi.WASAPISharedOutput.start() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__stop; // public void org.theko.sound.backends.wasapi.WASAPISharedOutput.stop() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__write_ArrayOf_byte__int__int; // public int org.theko.sound.backends.wasapi.WASAPISharedOutput.write(byte[],int,int) throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__close; // public void org.theko.sound.backends.wasapi.WASAPISharedOutput.close() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat; // public org.theko.sound.AudioFormat org.theko.sound.backends.wasapi.WASAPISharedOutput.open(org.theko.sound.AudioPort,org.theko.sound.AudioFormat) throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int; // public synchronized org.theko.sound.AudioFormat org.theko.sound.backends.wasapi.WASAPISharedOutput.open(org.theko.sound.AudioPort,org.theko.sound.AudioFormat,int) throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__isStarted; // public boolean org.theko.sound.backends.wasapi.WASAPISharedOutput.isStarted() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__available; // public int org.theko.sound.backends.wasapi.WASAPISharedOutput.available() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__drain; // public void org.theko.sound.backends.wasapi.WASAPISharedOutput.drain() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getBufferSize; // public int org.theko.sound.backends.wasapi.WASAPISharedOutput.getBufferSize() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getMicrosecondLatency; // public long org.theko.sound.backends.wasapi.WASAPISharedOutput.getMicrosecondLatency() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getMicrosecondPosition; // public long org.theko.sound.backends.wasapi.WASAPISharedOutput.getMicrosecondPosition() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getCurrentAudioPort; // public org.theko.sound.AudioPort org.theko.sound.backends.wasapi.WASAPISharedOutput.getCurrentAudioPort() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getFramePosition; // public long org.theko.sound.backends.wasapi.WASAPISharedOutput.getFramePosition() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__shutdown; // public void org.theko.sound.backends.wasapi.WASAPISharedBackend.shutdown() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__initialize; // public void org.theko.sound.backends.wasapi.WASAPISharedBackend.initialize() throws org.theko.sound.backends.AudioBackendException
        jmethodID mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat; // public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getPort(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getDefaultPort_org_theko_sound_AudioFlow; // public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getDefaultPort(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isInitialized; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isInitialized()
        jmethodID mtd__getInputBackend; // public org.theko.sound.backends.AudioInputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getInputBackend()
        jmethodID mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat,java.util.concurrent.atomic.AtomicReference) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat; // public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getAvailablePorts_org_theko_sound_AudioFlow; // public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__getAllPorts; // public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAllPorts() throws org.theko.sound.backends.BackendNotOpenException
        jmethodID mtd__isAudioPortSupported_org_theko_sound_AudioPort; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAudioPortSupported(org.theko.sound.AudioPort)
        jmethodID mtd__getOutputBackend; // public org.theko.sound.backends.AudioOutputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getOutputBackend()
        jmethodID mtd__isAvailableOnThisPlatform; // public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAvailableOnThisPlatform()
        jmethodID mtd__equals_java_lang_Object; // public boolean java.lang.Object.equals(java.lang.Object)

        Java_org_theko_sound_backends_wasapi_WASAPISharedOutput(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/backends/wasapi/WASAPISharedOutput");
            if (!clazz_local) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to find class 'org.theko.sound.backends.wasapi.WASAPISharedOutput'");
                return;
            }

            // Constructors
            ctor__ = env->GetMethodID(clazz_local, "<init>", "()V");
            if (!ctor__) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.backends.wasapi.WASAPISharedOutput()'");
                return;
            }

            // Fields
            fld__logger = env->GetStaticFieldID(clazz_local, "logger", "Lorg/slf4j/Logger;");
            if (!fld__logger) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'logger'");
                return;
            }
            fld__outputContextPtr = env->GetFieldID(clazz_local, "outputContextPtr", "J");
            if (!fld__outputContextPtr) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'outputContextPtr'");
                return;
            }
            fld__isOpen = env->GetFieldID(clazz_local, "isOpen", "Z");
            if (!fld__isOpen) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'isOpen'");
                return;
            }
            fld__isStarted = env->GetFieldID(clazz_local, "isStarted", "Z");
            if (!fld__isStarted) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'isStarted'");
                return;
            }
            fld__bufferSize = env->GetFieldID(clazz_local, "bufferSize", "I");
            if (!fld__bufferSize) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'bufferSize'");
                return;
            }
            fld__audioFormat = env->GetFieldID(clazz_local, "audioFormat", "Lorg/theko/sound/AudioFormat;");
            if (!fld__audioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'audioFormat'");
                return;
            }
            fld__port = env->GetFieldID(clazz_local, "port", "Lorg/theko/sound/AudioPort;");
            if (!fld__port) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'port'");
                return;
            }

            // Methods
            mtd__flush = env->GetMethodID(clazz_local, "flush", "()V");
            if (!mtd__flush) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'flush'");
                return;
            }
            mtd__isOpen = env->GetMethodID(clazz_local, "isOpen", "()Z");
            if (!mtd__isOpen) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isOpen'");
                return;
            }
            mtd__start = env->GetMethodID(clazz_local, "start", "()V");
            if (!mtd__start) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'start'");
                return;
            }
            mtd__stop = env->GetMethodID(clazz_local, "stop", "()V");
            if (!mtd__stop) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'stop'");
                return;
            }
            mtd__write_ArrayOf_byte__int__int = env->GetMethodID(clazz_local, "write", "([BII)I");
            if (!mtd__write_ArrayOf_byte__int__int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'write'");
                return;
            }
            mtd__close = env->GetMethodID(clazz_local, "close", "()V");
            if (!mtd__close) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'close'");
                return;
            }
            mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "open", "(Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;)Lorg/theko/sound/AudioFormat;");
            if (!mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'open'");
                return;
            }
            mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int = env->GetMethodID(clazz_local, "open", "(Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;I)Lorg/theko/sound/AudioFormat;");
            if (!mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'open'");
                return;
            }
            mtd__isStarted = env->GetMethodID(clazz_local, "isStarted", "()Z");
            if (!mtd__isStarted) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isStarted'");
                return;
            }
            mtd__available = env->GetMethodID(clazz_local, "available", "()I");
            if (!mtd__available) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'available'");
                return;
            }
            mtd__drain = env->GetMethodID(clazz_local, "drain", "()V");
            if (!mtd__drain) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'drain'");
                return;
            }
            mtd__getBufferSize = env->GetMethodID(clazz_local, "getBufferSize", "()I");
            if (!mtd__getBufferSize) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getBufferSize'");
                return;
            }
            mtd__getMicrosecondLatency = env->GetMethodID(clazz_local, "getMicrosecondLatency", "()J");
            if (!mtd__getMicrosecondLatency) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getMicrosecondLatency'");
                return;
            }
            mtd__getMicrosecondPosition = env->GetMethodID(clazz_local, "getMicrosecondPosition", "()J");
            if (!mtd__getMicrosecondPosition) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getMicrosecondPosition'");
                return;
            }
            mtd__getCurrentAudioPort = env->GetMethodID(clazz_local, "getCurrentAudioPort", "()Lorg/theko/sound/AudioPort;");
            if (!mtd__getCurrentAudioPort) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getCurrentAudioPort'");
                return;
            }
            mtd__getFramePosition = env->GetMethodID(clazz_local, "getFramePosition", "()J");
            if (!mtd__getFramePosition) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getFramePosition'");
                return;
            }
            mtd__shutdown = env->GetMethodID(clazz_local, "shutdown", "()V");
            if (!mtd__shutdown) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'shutdown'");
                return;
            }
            mtd__initialize = env->GetMethodID(clazz_local, "initialize", "()V");
            if (!mtd__initialize) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'initialize'");
                return;
            }
            mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "getPort", "(Lorg/theko/sound/AudioFlow;Lorg/theko/sound/AudioFormat;)Ljava/util/Optional;");
            if (!mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getPort'");
                return;
            }
            mtd__getDefaultPort_org_theko_sound_AudioFlow = env->GetMethodID(clazz_local, "getDefaultPort", "(Lorg/theko/sound/AudioFlow;)Ljava/util/Optional;");
            if (!mtd__getDefaultPort_org_theko_sound_AudioFlow) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getDefaultPort'");
                return;
            }
            mtd__isInitialized = env->GetMethodID(clazz_local, "isInitialized", "()Z");
            if (!mtd__isInitialized) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isInitialized'");
                return;
            }
            mtd__getInputBackend = env->GetMethodID(clazz_local, "getInputBackend", "()Lorg/theko/sound/backends/AudioInputBackend;");
            if (!mtd__getInputBackend) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getInputBackend'");
                return;
            }
            mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference = env->GetMethodID(clazz_local, "isFormatSupported", "(Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;Ljava/util/concurrent/atomic/AtomicReference;)Z");
            if (!mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isFormatSupported'");
                return;
            }
            mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "isFormatSupported", "(Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;)Z");
            if (!mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isFormatSupported'");
                return;
            }
            mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat = env->GetMethodID(clazz_local, "getAvailablePorts", "(Lorg/theko/sound/AudioFlow;Lorg/theko/sound/AudioFormat;)Ljava/util/Collection;");
            if (!mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getAvailablePorts'");
                return;
            }
            mtd__getAvailablePorts_org_theko_sound_AudioFlow = env->GetMethodID(clazz_local, "getAvailablePorts", "(Lorg/theko/sound/AudioFlow;)Ljava/util/Collection;");
            if (!mtd__getAvailablePorts_org_theko_sound_AudioFlow) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getAvailablePorts'");
                return;
            }
            mtd__getAllPorts = env->GetMethodID(clazz_local, "getAllPorts", "()Ljava/util/Collection;");
            if (!mtd__getAllPorts) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getAllPorts'");
                return;
            }
            mtd__isAudioPortSupported_org_theko_sound_AudioPort = env->GetMethodID(clazz_local, "isAudioPortSupported", "(Lorg/theko/sound/AudioPort;)Z");
            if (!mtd__isAudioPortSupported_org_theko_sound_AudioPort) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isAudioPortSupported'");
                return;
            }
            mtd__getOutputBackend = env->GetMethodID(clazz_local, "getOutputBackend", "()Lorg/theko/sound/backends/AudioOutputBackend;");
            if (!mtd__getOutputBackend) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getOutputBackend'");
                return;
            }
            mtd__isAvailableOnThisPlatform = env->GetMethodID(clazz_local, "isAvailableOnThisPlatform", "()Z");
            if (!mtd__isAvailableOnThisPlatform) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'isAvailableOnThisPlatform'");
                return;
            }
            mtd__equals_java_lang_Object = env->GetMethodID(clazz_local, "equals", "(Ljava/lang/Object;)Z");
            if (!mtd__equals_java_lang_Object) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'equals'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            
            initialized = true;
        }

    public:
        ~Java_org_theko_sound_backends_wasapi_WASAPISharedOutput() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* get(JNIEnv* env) {
            if (!env) return nullptr;
            if (!Java_org_theko_sound_backends_wasapi_WASAPISharedOutput::jvm) {
                env->GetJavaVM(&Java_org_theko_sound_backends_wasapi_WASAPISharedOutput::jvm);
            }
            static std::mutex mtx;
            static std::unique_ptr<Java_org_theko_sound_backends_wasapi_WASAPISharedOutput> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!instance || !instance->isValid()) {
                instance.reset(new Java_org_theko_sound_backends_wasapi_WASAPISharedOutput(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Field getters
        inline static jfieldID getfld__logger(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__logger;
        }
        inline static jfieldID getfld__outputContextPtr(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__outputContextPtr;
        }
        inline static jfieldID getfld__isOpen(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__isOpen;
        }
        inline static jfieldID getfld__isStarted(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__isStarted;
        }
        inline static jfieldID getfld__bufferSize(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__bufferSize;
        }
        inline static jfieldID getfld__audioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__audioFormat;
        }
        inline static jfieldID getfld__port(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__port;
        }

        // Constructor getters
        inline static jmethodID getctor__(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__;
        }

        // Method getters
        inline static jmethodID getmtd__flush(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__flush;
        }
        inline static jmethodID getmtd__isOpen(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isOpen;
        }
        inline static jmethodID getmtd__start(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__start;
        }
        inline static jmethodID getmtd__stop(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__stop;
        }
        inline static jmethodID getmtd__write_ArrayOf_byte__int__int(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__write_ArrayOf_byte__int__int;
        }
        inline static jmethodID getmtd__close(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__close;
        }
        inline static jmethodID getmtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int;
        }
        inline static jmethodID getmtd__isStarted(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isStarted;
        }
        inline static jmethodID getmtd__available(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__available;
        }
        inline static jmethodID getmtd__drain(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__drain;
        }
        inline static jmethodID getmtd__getBufferSize(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getBufferSize;
        }
        inline static jmethodID getmtd__getMicrosecondLatency(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getMicrosecondLatency;
        }
        inline static jmethodID getmtd__getMicrosecondPosition(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getMicrosecondPosition;
        }
        inline static jmethodID getmtd__getCurrentAudioPort(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getCurrentAudioPort;
        }
        inline static jmethodID getmtd__getFramePosition(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getFramePosition;
        }
        inline static jmethodID getmtd__shutdown(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__shutdown;
        }
        inline static jmethodID getmtd__initialize(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__initialize;
        }
        inline static jmethodID getmtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__getDefaultPort_org_theko_sound_AudioFlow(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getDefaultPort_org_theko_sound_AudioFlow;
        }
        inline static jmethodID getmtd__isInitialized(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isInitialized;
        }
        inline static jmethodID getmtd__getInputBackend(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getInputBackend;
        }
        inline static jmethodID getmtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference;
        }
        inline static jmethodID getmtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
        }
        inline static jmethodID getmtd__getAvailablePorts_org_theko_sound_AudioFlow(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getAvailablePorts_org_theko_sound_AudioFlow;
        }
        inline static jmethodID getmtd__getAllPorts(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getAllPorts;
        }
        inline static jmethodID getmtd__isAudioPortSupported_org_theko_sound_AudioPort(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isAudioPortSupported_org_theko_sound_AudioPort;
        }
        inline static jmethodID getmtd__getOutputBackend(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getOutputBackend;
        }
        inline static jmethodID getmtd__isAvailableOnThisPlatform(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__isAvailableOnThisPlatform;
        }
        inline static jmethodID getmtd__equals_java_lang_Object(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__equals_java_lang_Object;
        }

        // Fabric methods for constructors
        // Instance creation method for public org.theko.sound.backends.wasapi.WASAPISharedOutput()
        inline static jobject createInstance(JNIEnv* env) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor);
        }

        // Method wrappers
        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedOutput.flush() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static void flush(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__flush;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedOutput.isOpen() throws org.theko.sound.backends.AudioBackendException
        inline static jboolean isOpen(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isOpen;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedOutput.start() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static void start(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__start;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedOutput.stop() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static void stop(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__stop;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public int org.theko.sound.backends.wasapi.WASAPISharedOutput.write(byte[],int,int) throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jint write(JNIEnv* env, jobject obj, jbyteArray v0, jint v1, jint v2) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return (jint)0;
            jmethodID mtd = self->mtd__write_ArrayOf_byte__int__int;
            if (!mtd) return (jint)0;
            return env->CallIntMethod(obj, mtd, v0, v1, v2);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedOutput.close() throws org.theko.sound.backends.AudioBackendException
        inline static void close(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__close;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public org.theko.sound.AudioFormat org.theko.sound.backends.wasapi.WASAPISharedOutput.open(org.theko.sound.AudioPort,org.theko.sound.AudioFormat) throws org.theko.sound.backends.AudioBackendException
        inline static jobject open__org_theko_sound_AudioPort__org_theko_sound_AudioFormat(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public synchronized org.theko.sound.AudioFormat org.theko.sound.backends.wasapi.WASAPISharedOutput.open(org.theko.sound.AudioPort,org.theko.sound.AudioFormat,int) throws org.theko.sound.backends.AudioBackendException
        inline static jobject open__org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int(JNIEnv* env, jobject obj, jobject v0, jobject v1, jint v2) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__open_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__int;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0, v1, v2);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedOutput.isStarted() throws org.theko.sound.backends.AudioBackendException
        inline static jboolean isStarted(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isStarted;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd);
        }

        // Fabric method for public int org.theko.sound.backends.wasapi.WASAPISharedOutput.available() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jint available(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return (jint)0;
            jmethodID mtd = self->mtd__available;
            if (!mtd) return (jint)0;
            return env->CallIntMethod(obj, mtd);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedOutput.drain() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static void drain(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__drain;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public int org.theko.sound.backends.wasapi.WASAPISharedOutput.getBufferSize() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jint getBufferSize(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return (jint)0;
            jmethodID mtd = self->mtd__getBufferSize;
            if (!mtd) return (jint)0;
            return env->CallIntMethod(obj, mtd);
        }

        // Fabric method for public long org.theko.sound.backends.wasapi.WASAPISharedOutput.getMicrosecondLatency() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jlong getMicrosecondLatency(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return (jlong)0;
            jmethodID mtd = self->mtd__getMicrosecondLatency;
            if (!mtd) return (jlong)0;
            return env->CallLongMethod(obj, mtd);
        }

        // Fabric method for public long org.theko.sound.backends.wasapi.WASAPISharedOutput.getMicrosecondPosition() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jlong getMicrosecondPosition(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return (jlong)0;
            jmethodID mtd = self->mtd__getMicrosecondPosition;
            if (!mtd) return (jlong)0;
            return env->CallLongMethod(obj, mtd);
        }

        // Fabric method for public org.theko.sound.AudioPort org.theko.sound.backends.wasapi.WASAPISharedOutput.getCurrentAudioPort() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jobject getCurrentAudioPort(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getCurrentAudioPort;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public long org.theko.sound.backends.wasapi.WASAPISharedOutput.getFramePosition() throws org.theko.sound.backends.AudioBackendException,org.theko.sound.backends.BackendNotOpenException
        inline static jlong getFramePosition(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return (jlong)0;
            jmethodID mtd = self->mtd__getFramePosition;
            if (!mtd) return (jlong)0;
            return env->CallLongMethod(obj, mtd);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedBackend.shutdown() throws org.theko.sound.backends.AudioBackendException
        inline static void shutdown(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__shutdown;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public void org.theko.sound.backends.wasapi.WASAPISharedBackend.initialize() throws org.theko.sound.backends.AudioBackendException
        inline static void initialize(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return;
            jmethodID mtd = self->mtd__initialize;
            if (!mtd) return;
            env->CallVoidMethod(obj, mtd);
        }

        // Fabric method for public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getPort(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getPort(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getPort_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public java.util.Optional org.theko.sound.backends.wasapi.WASAPISharedBackend.getDefaultPort(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getDefaultPort(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getDefaultPort_org_theko_sound_AudioFlow;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isInitialized()
        inline static jboolean isInitialized(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isInitialized;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd);
        }

        // Fabric method for public org.theko.sound.backends.AudioInputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getInputBackend()
        inline static jobject getInputBackend(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getInputBackend;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat,java.util.concurrent.atomic.AtomicReference) throws org.theko.sound.backends.BackendNotOpenException
        inline static jboolean isFormatSupported__org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference(JNIEnv* env, jobject obj, jobject v0, jobject v1, jobject v2) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat__java_util_concurrent_atomic_AtomicReference;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0, v1, v2);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isFormatSupported(org.theko.sound.AudioPort,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        inline static jboolean isFormatSupported__org_theko_sound_AudioPort__org_theko_sound_AudioFormat(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isFormatSupported_org_theko_sound_AudioPort__org_theko_sound_AudioFormat;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow,org.theko.sound.AudioFormat) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getAvailablePorts__org_theko_sound_AudioFlow__org_theko_sound_AudioFormat(JNIEnv* env, jobject obj, jobject v0, jobject v1) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getAvailablePorts_org_theko_sound_AudioFlow__org_theko_sound_AudioFormat;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0, v1);
        }

        // Fabric method for public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAvailablePorts(org.theko.sound.AudioFlow) throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getAvailablePorts__org_theko_sound_AudioFlow(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getAvailablePorts_org_theko_sound_AudioFlow;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd, v0);
        }

        // Fabric method for public java.util.Collection org.theko.sound.backends.wasapi.WASAPISharedBackend.getAllPorts() throws org.theko.sound.backends.BackendNotOpenException
        inline static jobject getAllPorts(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getAllPorts;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAudioPortSupported(org.theko.sound.AudioPort)
        inline static jboolean isAudioPortSupported(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isAudioPortSupported_org_theko_sound_AudioPort;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0);
        }

        // Fabric method for public org.theko.sound.backends.AudioOutputBackend org.theko.sound.backends.wasapi.WASAPISharedBackend.getOutputBackend()
        inline static jobject getOutputBackend(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getOutputBackend;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPISharedBackend.isAvailableOnThisPlatform()
        inline static jboolean isAvailableOnThisPlatform(JNIEnv* env, jobject obj) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__isAvailableOnThisPlatform;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd);
        }

        // Fabric method for public boolean java.lang.Object.equals(java.lang.Object)
        inline static jboolean equals(JNIEnv* env, jobject obj, jobject v0) {
            Java_org_theko_sound_backends_wasapi_WASAPISharedOutput* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__equals_java_lang_Object;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0);
        }

    // End of class declaration
};
