/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.backends.DeviceInvalidatedException'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/backends/DeviceInvalidatedException
class ThekoSound_DeviceInvalidatedException {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized
        jclass clazz;
        jmethodID ctor__java_lang_String; // public org.theko.sound.backends.DeviceInvalidatedException(java.lang.String)
        jmethodID ctor__java_lang_Throwable; // public org.theko.sound.backends.DeviceInvalidatedException(java.lang.Throwable)
        jmethodID ctor__java_lang_String__java_lang_Throwable; // public org.theko.sound.backends.DeviceInvalidatedException(java.lang.String,java.lang.Throwable)
        jmethodID mtd__toString; // public java.lang.String java.lang.Throwable.toString()
        jmethodID mtd__getMessage; // public java.lang.String java.lang.Throwable.getMessage()
        jmethodID mtd__equals_java_lang_Object; // public boolean java.lang.Object.equals(java.lang.Object)

        ThekoSound_DeviceInvalidatedException(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/backends/DeviceInvalidatedException");
            if (!clazz_local) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to find class 'org.theko.sound.backends.DeviceInvalidatedException'");
                return;
            }

            // Constructors
            ctor__java_lang_String = env->GetMethodID(clazz_local, "<init>", "(Ljava/lang/String;)V");
            if (!ctor__java_lang_String) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.backends.DeviceInvalidatedException(java.lang.String)'");
                return;
            }
            ctor__java_lang_Throwable = env->GetMethodID(clazz_local, "<init>", "(Ljava/lang/Throwable;)V");
            if (!ctor__java_lang_Throwable) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.backends.DeviceInvalidatedException(java.lang.Throwable)'");
                return;
            }
            ctor__java_lang_String__java_lang_Throwable = env->GetMethodID(clazz_local, "<init>", "(Ljava/lang/String;Ljava/lang/Throwable;)V");
            if (!ctor__java_lang_String__java_lang_Throwable) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.backends.DeviceInvalidatedException(java.lang.String,java.lang.Throwable)'");
                return;
            }

            // Methods
            mtd__toString = env->GetMethodID(clazz_local, "toString", "()Ljava/lang/String;");
            if (!mtd__toString) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'toString'");
                return;
            }
            mtd__getMessage = env->GetMethodID(clazz_local, "getMessage", "()Ljava/lang/String;");
            if (!mtd__getMessage) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getMessage'");
                return;
            }
            mtd__equals_java_lang_Object = env->GetMethodID(clazz_local, "equals", "(Ljava/lang/Object;)Z");
            if (!mtd__equals_java_lang_Object) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'equals'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            initialized = true;
        }

    public:
        ~ThekoSound_DeviceInvalidatedException() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static ThekoSound_DeviceInvalidatedException* get(JNIEnv* env) {
            if (!env) return nullptr;
            if (!ThekoSound_DeviceInvalidatedException::jvm) {
                env->GetJavaVM(&ThekoSound_DeviceInvalidatedException::jvm);
            }
            static std::mutex mtx;
            static std::unique_ptr<ThekoSound_DeviceInvalidatedException> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!instance || !instance->isValid()) {
                instance.reset(new ThekoSound_DeviceInvalidatedException(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Constructor getters
        inline static jmethodID getctor__java_lang_String(JNIEnv* env) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__java_lang_String;
        }
        inline static jmethodID getctor__java_lang_Throwable(JNIEnv* env) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__java_lang_Throwable;
        }
        inline static jmethodID getctor__java_lang_String__java_lang_Throwable(JNIEnv* env) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__java_lang_String__java_lang_Throwable;
        }

        // Method getters
        inline static jmethodID getmtd__toString(JNIEnv* env) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__toString;
        }
        inline static jmethodID getmtd__getMessage(JNIEnv* env) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getMessage;
        }
        inline static jmethodID getmtd__equals_java_lang_Object(JNIEnv* env) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__equals_java_lang_Object;
        }

        // Fabric methods for constructors
        // Instance creation method for public org.theko.sound.backends.DeviceInvalidatedException(java.lang.String)
        inline static jobject createInstance(JNIEnv* env, jstring v0) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__java_lang_String;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor, v0);
        }

        // Instance creation method for public org.theko.sound.backends.DeviceInvalidatedException(java.lang.Throwable)
        inline static jobject createInstance(JNIEnv* env, jobject v0) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__java_lang_Throwable;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor, v0);
        }

        // Instance creation method for public org.theko.sound.backends.DeviceInvalidatedException(java.lang.String,java.lang.Throwable)
        inline static jobject createInstance(JNIEnv* env, jstring v0, jobject v1) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__java_lang_String__java_lang_Throwable;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor, v0, v1);
        }

        // Method wrappers
        // Fabric method for public java.lang.String java.lang.Throwable.toString()
        inline static jstring toString(JNIEnv* env, jobject obj) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__toString;
            if (!mtd) return nullptr;
            return (jstring) env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public java.lang.String java.lang.Throwable.getMessage()
        inline static jstring getMessage(JNIEnv* env, jobject obj) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getMessage;
            if (!mtd) return nullptr;
            return (jstring) env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public boolean java.lang.Object.equals(java.lang.Object)
        inline static jboolean equals(JNIEnv* env, jobject obj, jobject v0) {
            ThekoSound_DeviceInvalidatedException* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__equals_java_lang_Object;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0);
        }

    // End of class declaration
};
