/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.AudioFlow'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/AudioFlow
class ThekoSound_AudioFlow {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized

        // jclass cache
        jclass clazz;
        // jfieldID cache
        // public org.theko.sound.AudioFlow org.theko.sound.AudioFlow.IN
        jfieldID fld__IN;
        // public org.theko.sound.AudioFlow org.theko.sound.AudioFlow.OUT
        jfieldID fld__OUT;

        //jmethodID constructor cache
        // private org.theko.sound.AudioFlow(java.lang.String, int)
        jmethodID ctor__java_lang_String__int;

        // jmethodID cache
        // public java.lang.String org.theko.sound.AudioFlow.toString()
        jmethodID mtd__toString;
        // public org.theko.sound.AudioFlow[] org.theko.sound.AudioFlow.values()
        jmethodID mtd__values;
        // public org.theko.sound.AudioFlow org.theko.sound.AudioFlow.valueOf(java.lang.String)
        jmethodID mtd__valueOf_java_lang_String;
        // public org.theko.sound.AudioFlow org.theko.sound.AudioFlow.fromBoolean(boolean)
        jmethodID mtd__fromBoolean_boolean;

        ThekoSound_AudioFlow(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/AudioFlow");
            if (!clazz_local) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to find class 'org/theko/sound/AudioFlow'");
                return;
            }

            // Constructors
            ctor__java_lang_String__int = env->GetMethodID(clazz_local, "<init>", "(Ljava/lang/String;I)V");
            if (!ctor__java_lang_String__int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'private org.theko.sound.AudioFlow(java.lang.String,int)'");
                return;
            }

            // Fields
            fld__IN = env->GetStaticFieldID(clazz_local, "IN", "Lorg/theko/sound/AudioFlow;");
            if (!fld__IN) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'IN'");
                return;
            }
            fld__OUT = env->GetStaticFieldID(clazz_local, "OUT", "Lorg/theko/sound/AudioFlow;");
            if (!fld__OUT) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'OUT'");
                return;
            }

            // Methods
            mtd__toString = env->GetMethodID(clazz_local, "toString", "()Ljava/lang/String;");
            if (!mtd__toString) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'toString'");
                return;
            }
            mtd__values = env->GetStaticMethodID(clazz_local, "values", "()[Lorg/theko/sound/AudioFlow;");
            if (!mtd__values) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'values'");
                return;
            }
            mtd__valueOf_java_lang_String = env->GetStaticMethodID(clazz_local, "valueOf", "(Ljava/lang/String;)Lorg/theko/sound/AudioFlow;");
            if (!mtd__valueOf_java_lang_String) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'valueOf'");
                return;
            }
            mtd__fromBoolean_boolean = env->GetStaticMethodID(clazz_local, "fromBoolean", "(Z)Lorg/theko/sound/AudioFlow;");
            if (!mtd__fromBoolean_boolean) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'fromBoolean'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            initialized = true;
        }

    public:
        ~ThekoSound_AudioFlow() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static ThekoSound_AudioFlow* get(JNIEnv* env) {
            if (!env) return nullptr;
            static std::mutex mtx;
            static std::unique_ptr<ThekoSound_AudioFlow> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!ThekoSound_AudioFlow::jvm) {
                env->GetJavaVM(&ThekoSound_AudioFlow::jvm);
            }
            if (!instance || !instance->isValid()) {
                instance.reset(new ThekoSound_AudioFlow(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Field getters
        inline static jfieldID getfld__IN(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__IN;
        }
        inline static jfieldID getfld__OUT(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__OUT;
        }

        // Constructor getters
        inline static jmethodID getctor__java_lang_String__int(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__java_lang_String__int;
        }

        // Method getters
        inline static jmethodID getmtd__toString(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__toString;
        }
        inline static jmethodID getmtd__values(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__values;
        }
        inline static jmethodID getmtd__valueOf_java_lang_String(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__valueOf_java_lang_String;
        }
        inline static jmethodID getmtd__fromBoolean_boolean(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__fromBoolean_boolean;
        }

        // Fabric methods for constructors
        // Instance creation method for private org.theko.sound.AudioFlow(java.lang.String,int)
        inline static jobject createInstance(JNIEnv* env, jstring v0, jint v1) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__java_lang_String__int;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor, v0, v1);
        }

        // Method wrappers
        // Fabric method for public java.lang.String org.theko.sound.AudioFlow.toString()
        inline static jstring toString(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__toString;
            if (!mtd) return nullptr;
            return (jstring) env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public static org.theko.sound.AudioFlow[] org.theko.sound.AudioFlow.values()
        inline static jobjectArray values(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__values;
            if (!mtd) return nullptr;
            return (jobjectArray) env->CallStaticObjectMethod(self->clazz, mtd);
        }

        // Fabric method for public static org.theko.sound.AudioFlow org.theko.sound.AudioFlow.valueOf(java.lang.String)
        inline static jobject valueOf__java_lang_String(JNIEnv* env, jstring v0) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__valueOf_java_lang_String;
            if (!mtd) return nullptr;
            return env->CallStaticObjectMethod(self->clazz, mtd, v0);
        }

        // Fabric method for public static org.theko.sound.AudioFlow org.theko.sound.AudioFlow.fromBoolean(boolean)
        inline static jobject fromBoolean(JNIEnv* env, jboolean v0) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__fromBoolean_boolean;
            if (!mtd) return nullptr;
            return env->CallStaticObjectMethod(self->clazz, mtd, v0);
        }

        // Fabric field get for public static final org.theko.sound.AudioFlow org.theko.sound.AudioFlow.IN
        inline static jobject getField__IN(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__IN;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

        // Fabric field get for public static final org.theko.sound.AudioFlow org.theko.sound.AudioFlow.OUT
        inline static jobject getField__OUT(JNIEnv* env) {
            ThekoSound_AudioFlow* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__OUT;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

    // End of class declaration
};
