/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.AudioFormat$Builder'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/AudioFormat$Builder
class ThekoSound_AudioFormat_Builder {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized

        // jclass cache
        jclass clazz;
        // jfieldID cache
        // private boolean org.theko.sound.AudioFormat.Builder.bigEndian
        jfieldID fld__bigEndian;
        // private int org.theko.sound.AudioFormat.Builder.bitsPerSample
        jfieldID fld__bitsPerSample;
        // private int org.theko.sound.AudioFormat.Builder.channels
        jfieldID fld__channels;
        // private org.theko.sound.AudioFormat.Encoding org.theko.sound.AudioFormat.Builder.encoding
        jfieldID fld__encoding;
        // private int org.theko.sound.AudioFormat.Builder.sampleRate
        jfieldID fld__sampleRate;

        // jmethodID constructor cache
        // public org.theko.sound.AudioFormat.Builder()
        jmethodID ctor__;

        // jmethodID cache
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.alaw()
        jmethodID mtd__alaw;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.bigEndian()
        jmethodID mtd__bigEndian;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.bigEndian(boolean)
        jmethodID mtd__bigEndian_boolean;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.bits(int)
        jmethodID mtd__bits_int;
        // public org.theko.sound.AudioFormat org.theko.sound.AudioFormat.Builder.build()
        jmethodID mtd__build;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.channels(int)
        jmethodID mtd__channels_int;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.encoding(org.theko.sound.AudioFormat.Encoding)
        jmethodID mtd__encoding_org_theko_sound_AudioFormat_Encoding;
        // public boolean java.lang.Object.equals(java.lang.Object)
        jmethodID mtd__equals_java_lang_Object;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.littleEndian()
        jmethodID mtd__littleEndian;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.mono()
        jmethodID mtd__mono;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.pcmFloat()
        jmethodID mtd__pcmFloat;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.rate(int)
        jmethodID mtd__rate_int;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.signed()
        jmethodID mtd__signed;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.stereo()
        jmethodID mtd__stereo;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.ulaw()
        jmethodID mtd__ulaw;
        // public org.theko.sound.AudioFormat.Builder org.theko.sound.AudioFormat.Builder.unsigned()
        jmethodID mtd__unsigned;

        ThekoSound_AudioFormat_Builder(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/AudioFormat$Builder");
            if (!clazz_local) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to find class 'org/theko/sound/AudioFormat$Builder'");
                return;
            }

            // Constructors
            ctor__ = env->GetMethodID(clazz_local, "<init>", "()V");
            if (!ctor__) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.AudioFormat$Builder()'");
                return;
            }

            // Fields
            fld__bigEndian = env->GetFieldID(clazz_local, "bigEndian", "Z");
            if (!fld__bigEndian) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'bigEndian'");
                return;
            }
            fld__bitsPerSample = env->GetFieldID(clazz_local, "bitsPerSample", "I");
            if (!fld__bitsPerSample) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'bitsPerSample'");
                return;
            }
            fld__channels = env->GetFieldID(clazz_local, "channels", "I");
            if (!fld__channels) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'channels'");
                return;
            }
            fld__encoding = env->GetFieldID(clazz_local, "encoding", "Lorg/theko/sound/AudioFormat$Encoding;");
            if (!fld__encoding) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'encoding'");
                return;
            }
            fld__sampleRate = env->GetFieldID(clazz_local, "sampleRate", "I");
            if (!fld__sampleRate) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'sampleRate'");
                return;
            }

            // Methods
            mtd__alaw = env->GetMethodID(clazz_local, "alaw", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__alaw) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'alaw'");
                return;
            }
            mtd__bigEndian = env->GetMethodID(clazz_local, "bigEndian", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__bigEndian) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'bigEndian'");
                return;
            }
            mtd__bigEndian_boolean = env->GetMethodID(clazz_local, "bigEndian", "(Z)Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__bigEndian_boolean) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'bigEndian'");
                return;
            }
            mtd__bits_int = env->GetMethodID(clazz_local, "bits", "(I)Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__bits_int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'bits'");
                return;
            }
            mtd__build = env->GetMethodID(clazz_local, "build", "()Lorg/theko/sound/AudioFormat;");
            if (!mtd__build) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'build'");
                return;
            }
            mtd__channels_int = env->GetMethodID(clazz_local, "channels", "(I)Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__channels_int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'channels'");
                return;
            }
            mtd__encoding_org_theko_sound_AudioFormat_Encoding = env->GetMethodID(clazz_local, "encoding", "(Lorg/theko/sound/AudioFormat$Encoding;)Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__encoding_org_theko_sound_AudioFormat_Encoding) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'encoding'");
                return;
            }
            mtd__equals_java_lang_Object = env->GetMethodID(clazz_local, "equals", "(Ljava/lang/Object;)Z");
            if (!mtd__equals_java_lang_Object) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'equals'");
                return;
            }
            mtd__littleEndian = env->GetMethodID(clazz_local, "littleEndian", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__littleEndian) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'littleEndian'");
                return;
            }
            mtd__mono = env->GetMethodID(clazz_local, "mono", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__mono) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'mono'");
                return;
            }
            mtd__pcmFloat = env->GetMethodID(clazz_local, "pcmFloat", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__pcmFloat) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'pcmFloat'");
                return;
            }
            mtd__rate_int = env->GetMethodID(clazz_local, "rate", "(I)Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__rate_int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'rate'");
                return;
            }
            mtd__signed = env->GetMethodID(clazz_local, "signed", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__signed) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'signed'");
                return;
            }
            mtd__stereo = env->GetMethodID(clazz_local, "stereo", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__stereo) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'stereo'");
                return;
            }
            mtd__ulaw = env->GetMethodID(clazz_local, "ulaw", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__ulaw) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'ulaw'");
                return;
            }
            mtd__unsigned = env->GetMethodID(clazz_local, "unsigned", "()Lorg/theko/sound/AudioFormat$Builder;");
            if (!mtd__unsigned) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'unsigned'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            initialized = true;
        }

    public:
        ~ThekoSound_AudioFormat_Builder() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static ThekoSound_AudioFormat_Builder* get(JNIEnv* env) {
            if (!env) return nullptr;
            static std::mutex mtx;
            static std::unique_ptr<ThekoSound_AudioFormat_Builder> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!ThekoSound_AudioFormat_Builder::jvm) {
                env->GetJavaVM(&ThekoSound_AudioFormat_Builder::jvm);
            }
            if (!instance || !instance->isValid()) {
                instance.reset(new ThekoSound_AudioFormat_Builder(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Field getters
        inline static jfieldID getfld__bigEndian(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__bigEndian;
        }
        inline static jfieldID getfld__bitsPerSample(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__bitsPerSample;
        }
        inline static jfieldID getfld__channels(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__channels;
        }
        inline static jfieldID getfld__encoding(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__encoding;
        }
        inline static jfieldID getfld__sampleRate(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__sampleRate;
        }

        // Constructor getters
        inline static jmethodID getctor__(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__;
        }

        // Method getters
        inline static jmethodID getmtd__alaw(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__alaw;
        }
        inline static jmethodID getmtd__bigEndian(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__bigEndian;
        }
        inline static jmethodID getmtd__bigEndian_boolean(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__bigEndian_boolean;
        }
        inline static jmethodID getmtd__bits_int(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__bits_int;
        }
        inline static jmethodID getmtd__build(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__build;
        }
        inline static jmethodID getmtd__channels_int(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__channels_int;
        }
        inline static jmethodID getmtd__encoding_org_theko_sound_AudioFormat_Encoding(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__encoding_org_theko_sound_AudioFormat_Encoding;
        }
        inline static jmethodID getmtd__equals_java_lang_Object(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__equals_java_lang_Object;
        }
        inline static jmethodID getmtd__littleEndian(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__littleEndian;
        }
        inline static jmethodID getmtd__mono(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__mono;
        }
        inline static jmethodID getmtd__pcmFloat(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__pcmFloat;
        }
        inline static jmethodID getmtd__rate_int(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__rate_int;
        }
        inline static jmethodID getmtd__signed(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__signed;
        }
        inline static jmethodID getmtd__stereo(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__stereo;
        }
        inline static jmethodID getmtd__ulaw(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__ulaw;
        }
        inline static jmethodID getmtd__unsigned(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__unsigned;
        }

        // Fabric methods for constructors
        // Instance creation method for public org.theko.sound.AudioFormat$Builder()
        inline static jobject createInstance(JNIEnv* env) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__;
            if (!ctor) return nullptr;
            jobject ret = env->NewObject(self->clazz, ctor);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Method wrappers
        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.alaw()
        inline static jobject alaw(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__alaw;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.bigEndian()
        inline static jobject bigEndian__(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__bigEndian;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.bigEndian(boolean)
        inline static jobject bigEndian__boolean(JNIEnv* env, jobject obj, jboolean v0) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__bigEndian_boolean;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd, v0);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.bits(int)
        inline static jobject bits(JNIEnv* env, jobject obj, jint v0) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__bits_int;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd, v0);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat org.theko.sound.AudioFormat$Builder.build()
        inline static jobject build(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__build;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.channels(int)
        inline static jobject channels(JNIEnv* env, jobject obj, jint v0) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__channels_int;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd, v0);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.encoding(org.theko.sound.AudioFormat$Encoding)
        inline static jobject encoding(JNIEnv* env, jobject obj, jobject v0) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__encoding_org_theko_sound_AudioFormat_Encoding;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd, v0);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public boolean java.lang.Object.equals(java.lang.Object)
        inline static jboolean equals(JNIEnv* env, jobject obj, jobject v0) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__equals_java_lang_Object;
            if (!mtd) return JNI_FALSE;
            jboolean ret = env->CallBooleanMethod(obj, mtd, v0);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return JNI_FALSE;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.littleEndian()
        inline static jobject littleEndian(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__littleEndian;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.mono()
        inline static jobject mono(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__mono;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.pcmFloat()
        inline static jobject pcmFloat(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__pcmFloat;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.rate(int)
        inline static jobject rate(JNIEnv* env, jobject obj, jint v0) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__rate_int;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd, v0);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.signed()
        inline static jobject signed(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__signed;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.stereo()
        inline static jobject stereo(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__stereo;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.ulaw()
        inline static jobject ulaw(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__ulaw;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

        // Fabric method for public org.theko.sound.AudioFormat$Builder org.theko.sound.AudioFormat$Builder.unsigned()
        inline static jobject unsigned(JNIEnv* env, jobject obj) {
            ThekoSound_AudioFormat_Builder* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__unsigned;
            if (!mtd) return nullptr;
            jobject ret = env->CallObjectMethod(obj, mtd);
            if (env->ExceptionCheck()) {
                env->ExceptionDescribe();
                env->ExceptionClear();
                return nullptr;
            }
            return ret;
        }

    // End of class declaration
};
