/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.AudioFormat$Encoding'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/AudioFormat$Encoding
class ThekoSound_AudioFormat_Encoding {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized
        jclass clazz;
        jfieldID fld__PCM_UNSIGNED; // public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.PCM_UNSIGNED
        jfieldID fld__PCM_SIGNED; // public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.PCM_SIGNED
        jfieldID fld__PCM_FLOAT; // public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.PCM_FLOAT
        jfieldID fld__ULAW; // public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.ULAW
        jfieldID fld__ALAW; // public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.ALAW
        jmethodID ctor__java_lang_String__int; // private org.theko.sound.AudioFormat$Encoding(java.lang.String,int)
        jmethodID mtd__values; // public static org.theko.sound.AudioFormat$Encoding[] org.theko.sound.AudioFormat$Encoding.values()
        jmethodID mtd__valueOf_java_lang_String; // public static org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.valueOf(java.lang.String)

        ThekoSound_AudioFormat_Encoding(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/AudioFormat$Encoding");
            if (!clazz_local) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to find class 'org.theko.sound.AudioFormat$Encoding'");
                return;
            }

            // Constructors
            ctor__java_lang_String__int = env->GetMethodID(clazz_local, "<init>", "(Ljava/lang/String;I)V");
            if (!ctor__java_lang_String__int) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'private org.theko.sound.AudioFormat$Encoding(java.lang.String,int)'");
                return;
            }

            // Fields
            fld__PCM_UNSIGNED = env->GetStaticFieldID(clazz_local, "PCM_UNSIGNED", "Lorg/theko/sound/AudioFormat$Encoding;");
            if (!fld__PCM_UNSIGNED) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'PCM_UNSIGNED'");
                return;
            }
            fld__PCM_SIGNED = env->GetStaticFieldID(clazz_local, "PCM_SIGNED", "Lorg/theko/sound/AudioFormat$Encoding;");
            if (!fld__PCM_SIGNED) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'PCM_SIGNED'");
                return;
            }
            fld__PCM_FLOAT = env->GetStaticFieldID(clazz_local, "PCM_FLOAT", "Lorg/theko/sound/AudioFormat$Encoding;");
            if (!fld__PCM_FLOAT) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'PCM_FLOAT'");
                return;
            }
            fld__ULAW = env->GetStaticFieldID(clazz_local, "ULAW", "Lorg/theko/sound/AudioFormat$Encoding;");
            if (!fld__ULAW) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'ULAW'");
                return;
            }
            fld__ALAW = env->GetStaticFieldID(clazz_local, "ALAW", "Lorg/theko/sound/AudioFormat$Encoding;");
            if (!fld__ALAW) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'ALAW'");
                return;
            }

            // Methods
            mtd__values = env->GetStaticMethodID(clazz_local, "values", "()[Lorg/theko/sound/AudioFormat$Encoding;");
            if (!mtd__values) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'values'");
                return;
            }
            mtd__valueOf_java_lang_String = env->GetStaticMethodID(clazz_local, "valueOf", "(Ljava/lang/String;)Lorg/theko/sound/AudioFormat$Encoding;");
            if (!mtd__valueOf_java_lang_String) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'valueOf'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            initialized = true;
        }

    public:
        ~ThekoSound_AudioFormat_Encoding() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static ThekoSound_AudioFormat_Encoding* get(JNIEnv* env) {
            if (!env) return nullptr;
            if (!ThekoSound_AudioFormat_Encoding::jvm) {
                env->GetJavaVM(&ThekoSound_AudioFormat_Encoding::jvm);
            }
            static std::mutex mtx;
            static std::unique_ptr<ThekoSound_AudioFormat_Encoding> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!instance || !instance->isValid()) {
                instance.reset(new ThekoSound_AudioFormat_Encoding(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Field getters
        inline static jfieldID getfld__PCM_UNSIGNED(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__PCM_UNSIGNED;
        }
        inline static jfieldID getfld__PCM_SIGNED(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__PCM_SIGNED;
        }
        inline static jfieldID getfld__PCM_FLOAT(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__PCM_FLOAT;
        }
        inline static jfieldID getfld__ULAW(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__ULAW;
        }
        inline static jfieldID getfld__ALAW(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__ALAW;
        }

        // Constructor getters
        inline static jmethodID getctor__java_lang_String__int(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__java_lang_String__int;
        }

        // Method getters
        inline static jmethodID getmtd__values(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__values;
        }
        inline static jmethodID getmtd__valueOf_java_lang_String(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__valueOf_java_lang_String;
        }

        // Fabric methods for constructors
        // Instance creation method for private org.theko.sound.AudioFormat$Encoding(java.lang.String,int)
        inline static jobject createInstance(JNIEnv* env, jstring v0, jint v1) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__java_lang_String__int;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor, v0, v1);
        }

        // Method wrappers
        // Fabric method for public static org.theko.sound.AudioFormat$Encoding[] org.theko.sound.AudioFormat$Encoding.values()
        inline static jobjectArray values(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__values;
            if (!mtd) return nullptr;
            return (jobjectArray) env->CallStaticObjectMethod(self->clazz, mtd);
        }

        // Fabric method for public static org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.valueOf(java.lang.String)
        inline static jobject valueOf__java_lang_String(JNIEnv* env, jstring v0) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__valueOf_java_lang_String;
            if (!mtd) return nullptr;
            return env->CallStaticObjectMethod(self->clazz, mtd, v0);
        }

        // Fabric field get for public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.PCM_UNSIGNED
        inline static jobject getField__PCM_UNSIGNED(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__PCM_UNSIGNED;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

        // Fabric field get for public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.PCM_SIGNED
        inline static jobject getField__PCM_SIGNED(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__PCM_SIGNED;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

        // Fabric field get for public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.PCM_FLOAT
        inline static jobject getField__PCM_FLOAT(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__PCM_FLOAT;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

        // Fabric field get for public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.ULAW
        inline static jobject getField__ULAW(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__ULAW;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

        // Fabric field get for public static final org.theko.sound.AudioFormat$Encoding org.theko.sound.AudioFormat$Encoding.ALAW
        inline static jobject getField__ALAW(JNIEnv* env) {
            ThekoSound_AudioFormat_Encoding* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jfieldID fld = self->fld__ALAW;
            if (!fld) return nullptr;
            return env->GetStaticObjectField(self->clazz, fld);
        }

    // End of class declaration
};
