/*
 * DO NOT EDIT THIS FILE - it is machine generated.
 * JNI single-header class with wrappers and caching for 'org.theko.sound.backends.wasapi.WASAPIPortHandle'.
 */
#pragma once
#include <jni.h>
#include <mutex>
#include <memory>

// Target class: org/theko/sound/backends/wasapi/WASAPIPortHandle
class ThekoSound_WASAPIPortHandle {
    private:
        static inline JavaVM* jvm = nullptr;

        // Method to get JNIEnv for current thread
        static JNIEnv* getEnv(bool* attached = nullptr) {
            if (!jvm) return nullptr;
            JNIEnv* env = nullptr;
            if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                if (attached) *attached = false;
                return env;
            }
            if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                return nullptr;
            }
            if (attached) *attached = true;
            return env;
        }

        bool initialized = false; // True if all values are initialized

        // jclass cache
        jclass clazz;
        // jfieldID cache
        // private java.lang.String org.theko.sound.backends.wasapi.WASAPIPortHandle.handle
        jfieldID fld__handle;

        // jmethodID constructor cache
        // public org.theko.sound.backends.wasapi.WASAPIPortHandle(java.lang.String)
        jmethodID ctor__java_lang_String;

        // jmethodID cache
        // public boolean org.theko.sound.backends.wasapi.WASAPIPortHandle.equals(java.lang.Object)
        jmethodID mtd__equals_java_lang_Object;
        // public java.lang.String org.theko.sound.backends.wasapi.WASAPIPortHandle.getHandle()
        jmethodID mtd__getHandle;
        // public java.lang.Class org.theko.sound.backends.wasapi.WASAPIPortHandle.getRelatedBackend()
        jmethodID mtd__getRelatedBackend;
        // public java.lang.String org.theko.sound.backends.wasapi.WASAPIPortHandle.toString()
        jmethodID mtd__toString;

        ThekoSound_WASAPIPortHandle(JNIEnv* env) {
            initialized = false; // Reinitialize
            if (!env) return;
            jclass clazz_local = env->FindClass("org/theko/sound/backends/wasapi/WASAPIPortHandle");
            if (!clazz_local) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to find class 'org/theko/sound/backends/wasapi/WASAPIPortHandle'");
                return;
            }

            // Constructors
            ctor__java_lang_String = env->GetMethodID(clazz_local, "<init>", "(Ljava/lang/String;)V");
            if (!ctor__java_lang_String) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get constructor 'public org.theko.sound.backends.wasapi.WASAPIPortHandle(java.lang.String)'");
                return;
            }

            // Fields
            fld__handle = env->GetFieldID(clazz_local, "handle", "Ljava/lang/String;");
            if (!fld__handle) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get field 'handle'");
                return;
            }

            // Methods
            mtd__equals_java_lang_Object = env->GetMethodID(clazz_local, "equals", "(Ljava/lang/Object;)Z");
            if (!mtd__equals_java_lang_Object) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'equals'");
                return;
            }
            mtd__getHandle = env->GetMethodID(clazz_local, "getHandle", "()Ljava/lang/String;");
            if (!mtd__getHandle) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getHandle'");
                return;
            }
            mtd__getRelatedBackend = env->GetMethodID(clazz_local, "getRelatedBackend", "()Ljava/lang/Class;");
            if (!mtd__getRelatedBackend) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'getRelatedBackend'");
                return;
            }
            mtd__toString = env->GetMethodID(clazz_local, "toString", "()Ljava/lang/String;");
            if (!mtd__toString) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "Failed to get method 'toString'");
                return;
            }

            clazz = (jclass) env->NewGlobalRef(clazz_local);
            env->DeleteLocalRef(clazz_local);
            if (!clazz) {
                env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                return;
            }
            initialized = true;
        }

    public:
        ~ThekoSound_WASAPIPortHandle() {
            if (clazz) {
                bool attached = false;
                JNIEnv* env = getEnv(&attached);
                if (env) {
                    env->DeleteGlobalRef(clazz);
                    clazz = nullptr;
                }
                if (attached && jvm) {
                    jvm->DetachCurrentThread();
                }
            }
        }

        inline bool isValid() const {
            return clazz && initialized;
        }

        static ThekoSound_WASAPIPortHandle* get(JNIEnv* env) {
            if (!env) return nullptr;
            static std::mutex mtx;
            static std::unique_ptr<ThekoSound_WASAPIPortHandle> instance;
        
            std::lock_guard<std::mutex> lock(mtx);
            if (!ThekoSound_WASAPIPortHandle::jvm) {
                env->GetJavaVM(&ThekoSound_WASAPIPortHandle::jvm);
            }
            if (!instance || !instance->isValid()) {
                instance.reset(new ThekoSound_WASAPIPortHandle(env));
            }
            return instance.get();
        }

        // Getters
        inline static jclass getClazz(JNIEnv* env) {
            return get(env)->clazz;
        }

        // Field getters
        inline static jfieldID getfld__handle(JNIEnv* env) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->fld__handle;
        }

        // Constructor getters
        inline static jmethodID getctor__java_lang_String(JNIEnv* env) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->ctor__java_lang_String;
        }

        // Method getters
        inline static jmethodID getmtd__equals_java_lang_Object(JNIEnv* env) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__equals_java_lang_Object;
        }
        inline static jmethodID getmtd__getHandle(JNIEnv* env) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getHandle;
        }
        inline static jmethodID getmtd__getRelatedBackend(JNIEnv* env) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__getRelatedBackend;
        }
        inline static jmethodID getmtd__toString(JNIEnv* env) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            return self->mtd__toString;
        }

        // Fabric methods for constructors
        // Instance creation method for public org.theko.sound.backends.wasapi.WASAPIPortHandle(java.lang.String)
        inline static jobject createInstance(JNIEnv* env, jstring v0) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID ctor = self->ctor__java_lang_String;
            if (!ctor) return nullptr;
            return env->NewObject(self->clazz, ctor, v0);
        }

        // Method wrappers
        // Fabric method for public boolean org.theko.sound.backends.wasapi.WASAPIPortHandle.equals(java.lang.Object)
        inline static jboolean equals(JNIEnv* env, jobject obj, jobject v0) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return JNI_FALSE;
            jmethodID mtd = self->mtd__equals_java_lang_Object;
            if (!mtd) return JNI_FALSE;
            return env->CallBooleanMethod(obj, mtd, v0);
        }

        // Fabric method for public java.lang.String org.theko.sound.backends.wasapi.WASAPIPortHandle.getHandle()
        inline static jstring getHandle(JNIEnv* env, jobject obj) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getHandle;
            if (!mtd) return nullptr;
            return (jstring) env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public java.lang.Class org.theko.sound.backends.wasapi.WASAPIPortHandle.getRelatedBackend()
        inline static jobject getRelatedBackend(JNIEnv* env, jobject obj) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__getRelatedBackend;
            if (!mtd) return nullptr;
            return env->CallObjectMethod(obj, mtd);
        }

        // Fabric method for public java.lang.String org.theko.sound.backends.wasapi.WASAPIPortHandle.toString()
        inline static jstring toString(JNIEnv* env, jobject obj) {
            ThekoSound_WASAPIPortHandle* self = get(env);
            if (!self || !self->isValid()) return nullptr;
            jmethodID mtd = self->mtd__toString;
            if (!mtd) return nullptr;
            return (jstring) env->CallObjectMethod(obj, mtd);
        }

    // End of class declaration
};
