/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_theko_sound_backends_wasapi_WASAPISharedBackend */

#ifndef _Included_org_theko_sound_backends_wasapi_WASAPISharedBackend
#define _Included_org_theko_sound_backends_wasapi_WASAPISharedBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedBackend
 * Method:    nInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedBackend_nInit
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedBackend
 * Method:    nShutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedBackend_nShutdown
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedBackend
 * Method:    nGetAllPorts
 * Signature: (J)[Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobjectArray JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedBackend_nGetAllPorts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedBackend
 * Method:    nGetDefaultPort
 * Signature: (JLorg/theko/sound/AudioFlow;)Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedBackend_nGetDefaultPort
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedBackend
 * Method:    nIsFormatSupported
 * Signature: (Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;Ljava/util/concurrent/atomic/AtomicReference;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedBackend_nIsFormatSupported
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
