/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_theko_sound_backend_wasapi_WASAPISharedOutput */

#ifndef _Included_org_theko_sound_backend_wasapi_WASAPISharedOutput
#define _Included_org_theko_sound_backend_wasapi_WASAPISharedOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nOpen
 * Signature: (Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;I)Lorg/theko/sound/AudioFormat;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nOpen
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nClose
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nStart
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nStop
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nFlush
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nDrain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nDrain
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nWrite
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nWrite
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nAvailable
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nGetBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nGetBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nGetFramePosition
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nGetFramePosition
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nGetMicrosecondLatency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nGetMicrosecondLatency
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    nGetCurrentAudioPort
 * Signature: ()Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_nGetCurrentAudioPort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
