/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_theko_sound_backends_wasapi_WASAPISharedInput */

#ifndef _Included_org_theko_sound_backends_wasapi_WASAPISharedInput
#define _Included_org_theko_sound_backends_wasapi_WASAPISharedInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nOpen
 * Signature: (Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;I)Lorg/theko/sound/AudioFormat;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nOpen
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nClose
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nStart
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nStop
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nFlush
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nDrain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nDrain
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nRead
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nRead
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nAvailable
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nGetBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nGetBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nGetFramePosition
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nGetFramePosition
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nGetMicrosecondLatency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nGetMicrosecondLatency
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backends_wasapi_WASAPISharedInput
 * Method:    nGetCurrentAudioPort
 * Signature: ()Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backends_wasapi_WASAPISharedInput_nGetCurrentAudioPort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
