/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_theko_sound_backend_wasapi_WASAPISharedOutput */

#ifndef _Included_org_theko_sound_backend_wasapi_WASAPISharedOutput
#define _Included_org_theko_sound_backend_wasapi_WASAPISharedOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    openOut0
 * Signature: (ZLorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;I)V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_openOut0
  (JNIEnv *, jobject, jboolean, jobject, jobject, jint);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    closeOut0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_closeOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    startOut0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_startOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    stopOut0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_stopOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    flushOut0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_flushOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    drainOut0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_drainOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    writeOut0
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_writeOut0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    availableOut0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_availableOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    getBufferSizeOut0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_getBufferSizeOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    getFramePositionOut0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_getFramePositionOut0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedOutput
 * Method:    getCurrentAudioPort0
 * Signature: ()Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedOutput_getCurrentAudioPort0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
