/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_theko_sound_backend_wasapi_WASAPISharedBackend */

#ifndef _Included_org_theko_sound_backend_wasapi_WASAPISharedBackend
#define _Included_org_theko_sound_backend_wasapi_WASAPISharedBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedBackend
 * Method:    initialize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedBackend_initialize0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedBackend
 * Method:    shutdown0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedBackend_shutdown0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedBackend
 * Method:    getAllPorts0
 * Signature: ()[Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobjectArray JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedBackend_getAllPorts0
  (JNIEnv *, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedBackend
 * Method:    getDefaultPort0
 * Signature: (Lorg/theko/sound/AudioFlow;)Lorg/theko/sound/AudioPort;
 */
JNIEXPORT jobject JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedBackend_getDefaultPort0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_theko_sound_backend_wasapi_WASAPISharedBackend
 * Method:    isFormatSupported0
 * Signature: (Lorg/theko/sound/AudioPort;Lorg/theko/sound/AudioFormat;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_theko_sound_backend_wasapi_WASAPISharedBackend_isFormatSupported0
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
