/*
 * Copyright 2025-present Alex Soloviov (aka Theko)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Parameter;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public class JNIClassCacheGenerator {

    private static final int INDENT = 4;
    private static final String PARAM_PREFIX = "v";

    private static final String AUTO_GEN_COMMENT = """
            /*
             * DO NOT EDIT THIS FILE - it is machine generated.
             * JNI single-header class with wrappers and caching for '%s'.
             */
            """;

    private static final String GET_JAVAVM = """
            // Method to get JNIEnv for current thread
            static JNIEnv* getEnv(bool* attached = nullptr) {
                if (!jvm) return nullptr;
                JNIEnv* env = nullptr;
                if (jvm->GetEnv((void**)&env, JNI_VERSION_1_6) == JNI_OK) {
                    if (attached) *attached = false;
                    return env;
                }
                if (jvm->AttachCurrentThread((void**)&env, nullptr) != JNI_OK) {
                    return nullptr;
                }
                if (attached) *attached = true;
                return env;
            }
            """;

    private static final String DESTRUCTOR = """
            ~%s() {
                if (clazz) {
                    bool attached = false;
                    JNIEnv* env = getEnv(&attached);
                    if (env) {
                        env->DeleteGlobalRef(clazz);
                        clazz = nullptr;
                    }
                    if (attached && jvm) {
                        jvm->DetachCurrentThread();
                    }
                }
            }
            """;

    private static final String SINGLETON_GET = """
            static %s* get(JNIEnv* env) {
                if (!env) return nullptr;
                static std::mutex mtx;
                static std::unique_ptr<%s> instance;

                std::lock_guard<std::mutex> lock(mtx);
                if (!%s::jvm) {
                    env->GetJavaVM(&%s::jvm);
                }
                if (!instance || !instance->isValid()) {
                    instance.reset(new %s(env));
                }
                return instance.get();
            }
            """;

    private static final String CHECK_CODE = """
            if (!%s) {
                if (clazz_local) env->DeleteLocalRef(clazz_local);
                env->ThrowNew(env->FindClass("java/lang/NullPointerException"), "%s");
                return%s;
            }
            """;

    public static String generate(Class<?> cls, String cppClassName) {
        StringBuilder sb = new StringBuilder();
        cppClassName = (cppClassName == null || cppClassName.isEmpty()) ? ("Java_" + sanitize(cls.getName())) : cppClassName;
        String jniClassName = cls.getName().replace('.', '/');

        // Auto-generated comment
        sb.append(String.format(AUTO_GEN_COMMENT, cls.getName()));

        // Include jni.h
        sb.append("#pragma once\n");
        sb.append(include("jni.h"));
        sb.append(include("mutex"));
        sb.append(include("memory"));
        sb.append("\n");

        // Class definition
        sb.append("// Target class: ").append(jniClassName).append("\n");
        sb.append("class ").append(cppClassName).append(" {\n");

        // Private fields jclass + fieldID + methodID
        sb.append(indent(1)).append("private:\n");
        sb.append(indent(2)).append("static inline JavaVM* jvm = nullptr;\n\n");
        sb.append(multilineIndent(GET_JAVAVM, 2)).append("\n");
        sb.append(indent(2)).append("bool initialized = false; // True if all values are initialized\n\n");
        sb.append(indent(2)).append("// jclass cache\n");
        sb.append(indent(2)).append("jclass clazz;\n");

        // Fields of type jclass
        Field[] fields = cls.getDeclaredFields();
        if (fields.length > 0) {
            Arrays.sort(fields, Comparator.comparing(Field::getName));
            sb.append(indent(2)).append("// jfieldID cache\n");
            for (Field f : fields) {
                if (f.isSynthetic()) continue;
                sb.append(indent(2)).append("// ").append(fieldInfo(f)).append("\n");
                sb.append(indent(2)).append("jfieldID ").append(fieldName(f)).append(";\n");
            }
            sb.append("\n");
        }

        // Constructors
        Constructor<?>[] ctors = cls.getDeclaredConstructors();
        if (ctors.length > 0) {
            // Sort constructors
            Arrays.sort(ctors, Comparator
                // Sort constructors by number of parameters
                .comparingInt(Constructor<?>::getParameterCount)
                // Sort constructors by parameter types
                .thenComparing(c -> {
                    Class<?>[] types = c.getParameterTypes();
                    StringBuilder sortsb = new StringBuilder();
                    for (Class<?> t : types) {
                        sortsb.append(t.getName()).append(",");
                    }
                    return sortsb.toString();
                })
            );
            sb.append(indent(2)).append("// jmethodID constructor cache\n");
            for (Constructor<?> ctor : ctors) {
                if (ctor.isSynthetic()) continue;
                sb.append(indent(2)).append("// ").append(constructorInfo(ctor)).append("\n");
                sb.append(indent(2)).append("jmethodID ").append(constructorFieldName(ctor)).append(";\n");
            }
            sb.append("\n");
        }

        // Public methods
        Set<String> seenMethods = new HashSet<>(); // to avoid duplicates
        Method[] methods = cls.getMethods();
        List<Method> overloadedMethods = findOverloaded(methods);
        if (methods.length > 0) {
            Arrays.sort(methods, Comparator
                .comparing(Method::getName)
                // Sort methods by number of parameters
                .thenComparingInt(m -> m.getParameterCount())
                // Sort methods by parameter types
                .thenComparing(m -> {
                    Class<?>[] types = m.getParameterTypes();
                    StringBuilder sortsb = new StringBuilder();
                    for (Class<?> t : types) {
                        sortsb.append(t.getName()).append(",");
                    }
                    return sortsb.toString();
                })
            );
            sb.append(indent(2)).append("// jmethodID cache\n");
            for (Method m : methods) {
                if (isIgnoredMethod(m)) continue;
                String key = methodKey(m);
                if (!seenMethods.add(key)) continue;

                sb.append(indent(2)).append("// ").append(methodInfo(m)).append("\n");
                sb.append(indent(2)).append("jmethodID ").append(methodFieldName(m)).append(";\n");
            }
        }

        // Class constructor
        sb.append("\n");
        sb.append(indent(2)).append(cppClassName).append("(JNIEnv* env) {\n");
        sb.append(indent(3)).append("initialized = false; // Reinitialize\n");
        // Check if JNIEnv is not null
        sb.append(indent(3)).append("if (!env) return;\n");

        // Get jclass for this class
        sb.append(indent(3)).append("jclass clazz_local = env->FindClass(\"").append(jniClassName).append("\");\n");
        sb.append(indent(3)).append("if (!clazz_local) {\n");
        sb.append(indent(4)).append("env->ThrowNew(env->FindClass(\"java/lang/RuntimeException\"), \"Failed to find class '").append(jniClassName).append("'\");\n");
        sb.append(indent(4)).append("return;\n");
        sb.append(indent(3)).append("}\n");
        sb.append("\n");

        // Obtain all constructors jmethodIDs
        if (ctors.length > 0) {
            sb.append(indent(3)).append("// Constructors\n");
            for (Constructor<?> c : ctors) {
                if (c.isSynthetic()) continue;
                // ctor = env->GetMethodID(clazz, "<init>", "(...)V");
                sb.append(indent(3)).append(constructorFieldName(c))
                        .append(" = env->GetMethodID(clazz_local, \"<init>\", \"")
                        .append(constructorJNISignature(c)).append("\");\n");

                // Check if constructor is valid
                sb.append(multilineIndent(String.format(CHECK_CODE, constructorFieldName(c), "Failed to get constructor '" + c.toString() + "'", ""), 3));
            }
            sb.append("\n");
        }

        // Obtain all jfieldIDs
        if (fields.length > 0) {
            sb.append(indent(3)).append("// Fields\n");
            for (Field f : fields) {
                if (f.isSynthetic()) continue;
                // fieldID = env->GetFieldID(clazz, "name", "type");
                boolean isStatic = Modifier.isStatic(f.getModifiers());
                String targetMethod = isStatic ? "GetStaticFieldID" : "GetFieldID";
                String name = fieldName(f);
                sb.append(indent(3)).append(name)
                        .append(" = env->").append(targetMethod).append("(clazz_local, \"").append(f.getName()).append("\", \"")
                        .append(JNISignature(f.getType())).append("\");\n");

                // Check if field is valid
                sb.append(multilineIndent(String.format(CHECK_CODE, name, "Failed to get field '" + f.getName() + "'", ""), 3));
            }
            sb.append("\n");
        }

        // Obtain all jmethodIDs
        seenMethods.clear();
        if (methods.length > 0) {
            sb.append(indent(3)).append("// Methods\n");
            for (Method m : methods) {
                if (isIgnoredMethod(m)) continue;
                String key = methodKey(m);
                if (!seenMethods.add(key)) continue;

                // methodID = env->GetMethodID(clazz, "name", "(...)type");
                boolean isStatic = Modifier.isStatic(m.getModifiers());
                String targetMethod = isStatic ? "GetStaticMethodID" : "GetMethodID";
                sb.append(indent(3)).append(methodFieldName(m))
                        .append(" = env->").append(targetMethod).append("(clazz_local, \"").append(m.getName())
                        .append("\", \"").append(methodJNISignature(m)).append("\");\n");

                // Check if method is valid
                sb.append(multilineIndent(String.format(CHECK_CODE, methodFieldName(m), "Failed to get method '" + m.getName() + "'", ""), 3));
            }
            sb.append("\n");
        }

        // Create global class reference, remove local reference
        final String finalConstruct = """
                clazz = (jclass) env->NewGlobalRef(clazz_local);
                env->DeleteLocalRef(clazz_local);
                if (!clazz) {
                    env->ThrowNew(env->FindClass("java/lang/RuntimeException"), "Failed to create global class reference");
                    return;
                }
                initialized = true;
                """;

        sb.append(multilineIndent(finalConstruct, 3));
        sb.append(indent(2)).append("}\n\n");

        // Create public methods
        sb.append(indent(1)).append("public:\n");

        // Create default destructor
        sb.append(multilineIndent(String.format(DESTRUCTOR, cppClassName), 2)).append("\n");

        // Create isValid method, return true if class is valid
        sb.append(indent(2)).append("inline bool isValid() const {\n");
        sb.append(indent(3)).append("return clazz && initialized;\n");
        sb.append(indent(2)).append("}\n\n");

        // Create get method to obtain singleton instance (thread-safe)
        sb.append(multilineIndent(String.format(SINGLETON_GET,
                cppClassName, cppClassName, cppClassName, cppClassName, cppClassName), 2));
        sb.append("\n");

        sb.append(indent(2)).append("// Getters\n");

        // Create get method to obtain jclass
        sb.append(indent(2)).append("inline static jclass getClazz(JNIEnv* env) {\n")
                .append(indent(3)).append("return get(env)->clazz;\n")
                .append(indent(2)).append("}\n");

        if (fields.length > 0) {
            sb.append("\n");
            sb.append(indent(2)).append("// Field getters\n");

            // Getters for jfieldID
            for (Field f : fields) {
                if (f.isSynthetic()) continue;
                sb.append(indent(2)).append("inline static jfieldID get").append(fieldName(f)).append("(JNIEnv* env) {\n");
                sb.append(indent(3)).append(cppClassName).append("* self = get(env);\n");
                sb.append(indent(3)).append("if (!self || !self->isValid()) return nullptr;\n");
                sb.append(indent(3)).append("return self->").append(fieldName(f)).append(";\n");
                sb.append(indent(2)).append("}\n");
            }
        }

        if (ctors.length > 0) {
            sb.append("\n");
            sb.append(indent(2)).append("// Constructor getters\n");

            // Getters for constructors
            for (Constructor<?> c : ctors) {
                if (c.isSynthetic()) continue;
                sb.append(indent(2)).append("inline static jmethodID get").append(constructorFieldName(c)).append("(JNIEnv* env) {\n");
                sb.append(indent(3)).append(cppClassName).append("* self = get(env);\n");
                sb.append(indent(3)).append("if (!self || !self->isValid()) return nullptr;\n");
                sb.append(indent(3)).append("return self->").append(constructorFieldName(c)).append(";\n");
                sb.append(indent(2)).append("}\n");
            }
        }

        if (methods.length > 0) {
            sb.append("\n");
            sb.append(indent(2)).append("// Method getters\n");

            // Getters for jmethodID
            seenMethods.clear();
            for (Method m : methods) {
                if (isIgnoredMethod(m)) continue;
                String key = methodKey(m);
                if (!seenMethods.add(key)) continue;
                sb.append(indent(2)).append("inline static jmethodID get").append(methodFieldName(m)).append("(JNIEnv* env) {\n");
                sb.append(indent(3)).append(cppClassName).append("* self = get(env);\n");
                sb.append(indent(3)).append("if (!self || !self->isValid()) return nullptr;\n");
                sb.append(indent(3)).append("return self->").append(methodFieldName(m)).append(";\n");
                sb.append(indent(2)).append("}\n");
            }
        }

        if (ctors.length > 0) {
            sb.append("\n");
            sb.append(indent(2)).append("// Fabric methods for constructors\n");

            // Create fabric methods for instance creation
            for (Constructor<?> c : ctors) {
                if (c.isSynthetic()) continue;
                sb.append(indent(2)).append("// Instance creation method for ").append(c.toString()).append("\n");
                sb.append(indent(2)).append("inline static jobject createInstance(JNIEnv* env");
                int idx = 0;
                for (Parameter p : c.getParameters()) {
                    sb.append(", ").append(JNIType(p.getType())).append(" ").append(PARAM_PREFIX).append(idx++);
                }
                sb.append(") {\n");
                sb.append(indent(3)).append(cppClassName).append("* self = get(env);\n");
                sb.append(indent(3)).append("if (!self || !self->isValid()) return nullptr;\n");
                sb.append(indent(3)).append("jmethodID ctor = self->").append(constructorFieldName(c)).append(";\n");
                sb.append(indent(3)).append("if (!ctor) return nullptr;\n");
                sb.append(indent(3)).append("jobject ret = env->NewObject(self->clazz, ctor");
                for (int i = 0; i < c.getParameterCount(); i++) {
                    sb.append(", ").append(PARAM_PREFIX).append(i);
                }
                sb.append(");\n");

                // Check for exceptions
                sb.append(indent(3)).append("if (env->ExceptionCheck()) {\n");
                sb.append(indent(4)).append("env->ExceptionDescribe();\n");
                sb.append(indent(4)).append("env->ExceptionClear();\n");
                sb.append(indent(4)).append("return nullptr;\n");
                sb.append(indent(3)).append("}\n");

                // Return
                sb.append(indent(3)).append("return ret;\n");
                sb.append(indent(2)).append("}\n\n");
            }
        }

        // Method wrappers used to call Java methods
        if (methods.length > 0) {
            sb.append(indent(2)).append("// Method wrappers\n");
            seenMethods.clear();
            for (Method m : methods) {
                if (isIgnoredMethod(m)) continue;
                String key = methodKey(m);
                if (!seenMethods.add(key)) continue;

                Class<?> ret = m.getReturnType();
                String retJNI = JNIType(ret);

                boolean isStatic = Modifier.isStatic(m.getModifiers());
                String callTarget = isStatic ? "self->clazz" : "obj";
                // Generate JNI method call name
                String targetMethodBase = "env->Call%s%sMethod";
                String targetMethod = String.format(targetMethodBase, isStatic ? "Static" : "", returnType(ret));

                boolean shouldReturn = ret != void.class;
                boolean shouldCast = shouldReturn && (ret == String.class || ret.isArray());

                String returnStatement = shouldReturn ? "return " + defaultReturnFromJNIType(retJNI) + ";" : "return;";

                sb.append(indent(2)).append("// Fabric method for ").append(m.toString()).append("\n");

                // Method declaration
                String fabricName = overloadedMethods.contains(m) ? m.getName() + "__" + methodParameterSignature(m) : m.getName();
                sb.append(indent(2)).append("inline static ").append(retJNI).append(" ").append(fabricName).append("(JNIEnv* env");
                if (!isStatic) sb.append(", jobject obj");

                int idx = 0;
                for (Parameter p : m.getParameters()) {
                    sb.append(", ").append(JNIType(p.getType())).append(" ").append(PARAM_PREFIX).append(idx++);
                }
                sb.append(") {\n");
                sb.append(indent(3)).append(cppClassName).append("* self = get(env);\n");
                sb.append(indent(3)).append("if (!self || !self->isValid()) ").append(returnStatement).append("\n");

                // Get method
                sb.append(indent(3)).append("jmethodID mtd = self->").append(methodFieldName(m)).append(";\n");
                sb.append(indent(3)).append("if (!mtd) ").append(returnStatement).append("\n");

                // Method call
                sb.append(indent(3));
                if (shouldReturn) sb.append(retJNI).append(" ret = ");
                if (shouldCast) sb.append("(").append(retJNI).append(") ");
                sb.append(targetMethod).append("(").append(callTarget).append(", mtd");
                for (int i = 0; i < m.getParameterCount(); i++) {
                    sb.append(", ").append(PARAM_PREFIX).append(i);
                }
                sb.append(");\n");
                
                // Check for exceptions
                sb.append(indent(3)).append("if (env->ExceptionCheck()) {\n");
                sb.append(indent(4)).append("env->ExceptionDescribe();\n");
                sb.append(indent(4)).append("env->ExceptionClear();\n");
                if (shouldReturn)
                    sb.append(indent(4)).append("return ").append(defaultReturnFromJNIType(retJNI)).append(";\n");
                sb.append(indent(3)).append("}\n");

                // Return
                if (shouldReturn)
                    sb.append(indent(3)).append("return ret;\n");
                sb.append(indent(2)).append("}\n\n");
            }
        }

        // Fields wrapper for get/set (if not final) values. Only for protected and public
        if (fields.length > 0) {
            for (Field f : fields) {
                if (f.isSynthetic()) continue;
                boolean isPublic = Modifier.isPublic(f.getModifiers()) || Modifier.isProtected(f.getModifiers());
                if (!isPublic) continue;

                Class<?> ret = f.getType();
                String retJNI = JNIType(ret);

                boolean isStatic = Modifier.isStatic(f.getModifiers());
                String targetMethodBase = "env->%s%s%sField";

                for (int i = 0; i < 2; i++) {
                    boolean isGet = i == 0;
                    if (!isGet && Modifier.isFinal(f.getModifiers())) continue;

                    // Generate JNI method call name
                    String targetMethod = String.format(targetMethodBase, isGet ? "Get" : "Set", isStatic ? "Static" : "", returnType(ret));

                    boolean shouldReturn = ret != void.class && isGet;
                    boolean shouldCast = shouldReturn && (ret == String.class || ret.isArray());

                    String returnStatement = shouldReturn ? "return " + defaultReturnFromJNIType(retJNI) + ";" : "return;";

                    sb.append(indent(2)).append("// Fabric field ").append(isGet ? "get " : "set ").append("for ").append(f.toString()).append("\n");

                    // Method declaration
                    sb.append(indent(2)).append("inline static ");
                    if (shouldReturn) sb.append(retJNI);
                    else sb.append("void");
                    sb.append(" ").append(isGet ? "get" : "set")
                            .append("Field__").append(sanitize(f.getName())).append("(JNIEnv* env");
                    if (!isStatic) sb.append(", jobject obj");

                    // Specify value if set
                    if (!isGet) {
                        sb.append(", ").append(retJNI).append(" value");
                    }
                    sb.append(") {\n");
                    sb.append(indent(3)).append(cppClassName).append("* self = get(env);\n");
                    sb.append(indent(3)).append("if (!self || !self->isValid()) ").append(returnStatement).append("\n");

                    // Get field
                    sb.append(indent(3)).append("jfieldID fld = self->").append(fieldName(f)).append(";\n");
                    sb.append(indent(3)).append("if (!fld) ").append(returnStatement).append("\n");

                    // Method call
                    sb.append(indent(3));
                    if (shouldReturn) sb.append("return ");
                    if (shouldCast) sb.append("(").append(retJNI).append(") ");
                    sb.append(targetMethod).append("(").append(isStatic ? "self->clazz" : "obj").append(", fld");
                    if (!isGet) sb.append(", value");
                    sb.append(");\n");
                    sb.append(indent(2)).append("}\n\n");
                }
            }
        }

        // End of class declaration
        sb.append(indent(1)).append("// End of class declaration\n");
        sb.append("};\n");

        return sb.toString();
    }

    // Codegen helpers

    private static String include(String header) {
        return String.format("#include <%s>\n", header);
    }

    /* Constructors */
    private static String constructorFieldName(Constructor<?> ctor) {
        return "ctor__" + constructorSignature(ctor);
    }

    private static String constructorSignature(Constructor<?> ctor) {
        return Arrays.stream(ctor.getParameterTypes())
                .map(JNIClassCacheGenerator::typeToString)
                .collect(Collectors.joining("__"));
    }

    private static String constructorJNISignature(Constructor<?> ctor) {
        return "(" + Arrays.stream(ctor.getParameterTypes())
                .map(JNIClassCacheGenerator::JNISignature)
                .collect(Collectors.joining()) + ")V";
    }

    private static String constructorInfo(Constructor<?> ctor) {
        String params = Arrays.stream(ctor.getParameterTypes())
                .map(JNIClassCacheGenerator::getClassName)
                .collect(Collectors.joining(", "));
        
        Class<?> declaring = ctor.getDeclaringClass();
        String className = getClassName(declaring);
        if (className == null) {
            className = declaring.getName();
        }

        String visibility = visibilityString(ctor.getModifiers());
        return String.format("%s %s(%s)", visibility, className, params);
    }

    /* Methods */
    private static String methodFieldName(Method method) {
        String sig = methodParameterSignature(method);
        if (sig.isEmpty()) {
            return "mtd__" + method.getName();
        } else {
            return "mtd__" + method.getName() + "_" + sig;
        }
    }

    private static String methodParameterSignature(Method method) {
        return Arrays.stream(method.getParameterTypes())
                .map(JNIClassCacheGenerator::typeToString)
                .collect(Collectors.joining("__"));
    }

    private static String methodJNISignature(Method method) {
        return "(" + Arrays.stream(method.getParameterTypes())
                .map(JNIClassCacheGenerator::JNISignature)
                .collect(Collectors.joining()) + ")" + JNISignature(method.getReturnType());
    }

    private static String methodKey(Method method) {
        return method.getName() + methodParameterSignature(method);
    }

    public static List<Method> findOverloaded(Method[] methods) {
        return Arrays.stream(methods)
                .collect(Collectors.groupingBy(Method::getName))
                .values().stream()
                .filter(list -> list.size() > 1)
                .flatMap(List::stream)
                .collect(Collectors.toList());
    }

    private static boolean isIgnoredMethod(Method method) {
        if (method.isSynthetic() || method.isBridge()) return true;
        Class<?> owner = method.getDeclaringClass();

        if (owner == Object.class && !method.getName().equals("equals")) return true;
        if (owner == Enum.class) return true;
            if (owner == Throwable.class) {
        String name = method.getName();
        if (name.equals("getMessage") || name.equals("toString")) return false;
            return true;
        }

        return false;
    }

    private static String methodInfo(Method method) {
        String params = Arrays.stream(method.getParameterTypes())
                .map(JNIClassCacheGenerator::getClassName)
                .collect(Collectors.joining(", "));

        Class<?> type = method.getReturnType();
        Class<?> owner = method.getDeclaringClass();
        String visibility = visibilityString(method.getModifiers());

        return String.format("%s %s %s.%s(%s)",
                visibility,
                getClassName(type),
                getClassName(owner),
                method.getName(),
                params);
    }

    /* Fields */
    private static String fieldName(Field field) {
        return "fld__" + sanitize(field.getName());
    }

    private static String fieldInfo(Field field) {
        Class<?> type = field.getType();
        Class<?> owner = field.getDeclaringClass();
        String visibility = visibilityString(field.getModifiers());
        return String.format("%s %s %s.%s", visibility, getClassName(type), getClassName(owner), field.getName());
    }

    /* Other Reflection helpers */
    private static String getClassName(Class<?> type) {
        String name = type.getCanonicalName();
        if (name == null) name = type.getName();
        return name;
    }

    /* Other JNI helpers */
    private static String visibilityString(int mod) {
        if (Modifier.isPublic(mod)) return "public";
        if (Modifier.isProtected(mod)) return "protected";
        if (Modifier.isPrivate(mod)) return "private";
        return "package-private";
    }

    private static String typeToString(Class<?> type) {
        if (type.isPrimitive()) {
            return type.getSimpleName(); // boolean, int, ...
        } else if (type.isArray()) {
            return "ArrayOf_" + typeToString(type.getComponentType());
        } else {
            return type.getName().replace('.', '_').replace('$', '_');
        }
    }

    private static String returnType(Class<?> type) {
        if (type == void.class) {
            return "Void";
        } else if (type.isPrimitive()) {
            return capitalize(type.getName());
        } else {
            return "Object";
        }
    }

    private static String JNISignature(Class<?> type) {
        if (type.isPrimitive()) {
            if (type == boolean.class) return "Z";
            if (type == byte.class) return "B";
            if (type == char.class) return "C";
            if (type == short.class) return "S";
            if (type == int.class) return "I";
            if (type == long.class) return "J";
            if (type == float.class) return "F";
            if (type == double.class) return "D";
            if (type == void.class) return "V";
        } else if (type.isArray()) {
            return "[" + JNISignature(type.getComponentType());
        } else {
            return "L" + type.getName().replace('.', '/') + ";";
        }
        return "";
    }

    private static String JNIType(Class<?> type) {
        if (type.isArray()) {
            if (type.getComponentType().isPrimitive()) {
                return primitiveToJNIType(type.getComponentType()) + "Array";
            } else {
                return "jobjectArray";
            }
        }
        return primitiveToJNIType(type);
    }

    private static String primitiveToJNIType(Class<?> type) {
        if (type.isPrimitive()) {
            if (type == boolean.class) return "jboolean";
            if (type == byte.class) return "jbyte";
            if (type == char.class) return "jchar";
            if (type == short.class) return "jshort";
            if (type == int.class) return "jint";
            if (type == long.class) return "jlong";
            if (type == float.class) return "jfloat";
            if (type == double.class) return "jdouble";
            if (type == void.class) return "void";
        } else if (type == String.class) {
            return "jstring";
        }
        return "jobject";
    }

    private static String defaultReturnFromJNIType(String type) {
        if (type.equals("jboolean")) return "JNI_FALSE";
        if (type.equals("jbyte")) return "(jbyte)0";
        if (type.equals("jchar")) return "(jchar)0";
        if (type.equals("jshort")) return "(jshort)0";
        if (type.equals("jint")) return "(jint)0";
        if (type.equals("jlong")) return "(jlong)0";
        if (type.equals("jfloat")) return "(jfloat)0.0f";
        if (type.equals("jdouble")) return "(jdouble)0.0";
        return "nullptr";
    }

    // String helpers

    private static String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private static String sanitize(String s) {
        return s.replaceAll("[^a-zA-Z0-9]", "_");
    }

    private static String indent(int n) {
        return " ".repeat(n * INDENT);
    }

    private static String multilineIndent(String s, int n) {
        String[] lines = s.split("\n");
        StringBuilder sb = new StringBuilder();
        for (String line : lines) sb.append(indent(n)).append(line).append("\n");
        return sb.toString();
    }
}